### ISSUE TITLE
Add websocket on DM to notify changes in consoles

### ISSUE THREAD

**Issue by donsez** [roboconf/roboconf-platform#102]
add websocket on DM to notify changes in consoles (TUI, Web-based, ...)
in order to avoid to poll the DM
(could be a student project)

**Comment by vincent-zurczak** [comment]
The most up-to-date implementation of Sockets with Jetty is in Jetty 9.
Clearly, we do not want to have 2 web servers to handle the REST application and the web sockets. So, we must keep everything in Jetty, and Jetty 9 is the solution. By default, Karaf 3.x comes with Jetty 8 (through the Pax-Web project). Karaf should use Pax-Web 4.x to support directly web sockets.

We can install Pax-Web 4.x in Karaf with...

```
feature:repo-add mvn:org.ops4j.pax.web/pax-web-features/4.0.1/xml/features
```

The real question is how to uninstall the other one at build time.
This will have to be asked on Karaf's mailing list. Given that supporting web sockets in Roboconf implies implementing a web socket, but also changing the distribution, and given the remaining time, this issue will be delayed to another release.

**Comment by vincent-zurczak** [comment]
I asked on [Karaf's mailing list](http://mail-archives.apache.org/mod_mbox/karaf-user/201502.mbox/%3C54D4F33B.6040507%40linagora.com%3E).
We will most likely try to use Karaf 4.0.x in the next weeks.
