### ISSUE TITLE
Add Monitoring Support

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#155]
Monitoring is about using tools to monitor machines (hosts) or applications (services).
Monitoring is different from autonomic management, although there are obvious relations.

Roboconf should stick with usual monitoring tools (such as Nagios, Shinken, Cacti for graphs, etc).
A first option that was studied consisted in updating Nagios (or any other tools) configuration, based on template files that would have been provided with the application. It appears to be unrealistic. That would require these tools to be on the same machine than the DM, and most of all, it would require the DM to run as root. But the most problematic aspect of this solution was that Roboconf was supposed to modify files that are **critical** for people in charge of monotoring systems. These teams would never accept Roboconf to modify **their configurations**.

Instead, Roboconf should be able to generate (on a regular basis) a file describing hosts and services that would be of interest for monitoring tools. It would then be up to the production teams to use this file and update their monitoring configuration. A Nagios (or whatever else) plugin is easily feasible to automate this update.

So, for every application, there could be a file to indicate which kind of components should be written in the file to generate, and which period should be used to regenerate this file. Roboconf will deduce by it self if a component indicates a host or a service.

For the moment, the generated file will have a fixed shape (not customisable).
This last point may change later.

**Comment by vincent-zurczak** [comment]
This issue is just about putting information for other tools.
You will have to determine...

* The syntax to define templates (e.g. to only publish VM IPs).
* The location of these templates.

As you suggested, it is possible for an application to define several templates.

* **my-app.nagios.tpl** for a Nagios template.
* **my-app.cacti.tpl** for a Cacti template. Etc.

**Comment by vincent-zurczak** [comment]
Hint: you only have to plug additional code in Manager.saveConfiguration( ... ).

**Comment by bourretp** [comment]
There are many divergences between the spec & the implementation.
Updating specification...
