### ISSUE TITLE
Instantiate an application N times

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#176]
For the moment, with Roboconf, one application = one ZIP file.
It is not possible to have several instances of a same application within Roboconf. But it should be possible.

The platform should be upgraded to manage a local repository of applications (ZIP file with meta-data) and several instances of these applications. This will most likely introduce the following changes:

* A dedicated REST API for application instances.
* A new web interface.
* A new organization of the DM's directory.

**Comment by vincent-zurczak** [comment]
This task should focus on...

* .... creating an **ApplicationTemplate** that will contain the graph and a directory.
* ... modifying the **Application** class. It will have a name, a description, an ApplicationTemplate and a collection of root instances.
* ... updating the remaining code: the core utilities, the REST services' implementation and the DM.

**Comment by gibello** [comment]
Salut,

Avoir un user/group roboconf, c'est bien joli... sauf que pour installer 
des packages, c'est root !
Donc, je doute que lancer l'agent sous un autre user que root soit 
terrible...

Par contre, pour le DM, çà devrait le faire !

A+,
  PY

**Comment by vincent-zurczak** [comment]
Wrong topic...
And JDeb can handle launching init.d services as the root user. But you have to deal with that in the **pom.xml** file. It is JDeb configuration that will manage this for you.
