### ISSUE TITLE
Inject parent variables in recipes

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#184]
For the moment, we can inject in a recipe...

1. The received imports.
2. The component's own variables.

It would be great to be able to inject ancestor variables.
As an example, the following bash script updates a web application deployed on Tomcat. The instances hierarchy gives *VM -> Tomcat -> Web application*.

```bash
#!/bin/bash

# Replace the properties
rm -f /tmp/coaps.properties
echo "op.url = $RSE_1_ip" > /tmp/my.properties
echo "op.user = toto" >> /tmp/my.properties
echo "op.pwd = secret" >> /tmp/my.properties

# Reload the application (assumption: Tomcat listens to the 8081 port)
wget http://localhost:8081/manager/text/reload?path=/coaps-openpaas-impl-0.0.1-SNAPSHOT
```

Rather than hard-coding the Tomcat port, we could simply get it from the Tomcat component.
The recipe's end would then look like...

```bash
wget http://localhost:${tomcat_port}/manager/text/reload?path=/coaps-openpaas-impl-0.0.1-SNAPSHOT
```

**Comment by vincent-zurczak** [comment]
I am still wondering whether this is a good idea or not.
It may be interesting for recipes, but it may also limit reusability. I do not know. What do you think?

@rpignolet @gibello @donsez @ykouki

**Comment by gibello** [comment]
Le 11/02/2015 11:30, Vincent Zurczak a écrit :
>
> I am still wondering whether this is a good idea or not.
> It may be interesting for recipes, but it may also limit reusability. 
> I do not know. What do you think?
>
> @rpignolet <https://github.com/rpignolet> @gibello 
> <https://github.com/gibello> @donsez <https://github.com/donsez> 
> @ykouki <https://github.com/ykouki>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/roboconf/roboconf-platform/issues/184#issuecomment-73860761>.
>
Do we *really* need that ?

And if so... is it only limited to ancestors ? (I mean, I don't need to 
be deployed in a Tomcat to require the Tomcat's port ??) Of course, 
being able to inject... anything would mean having access to the whole 
graph (and I'm not even sure it is possible). But if we open the door...

So, unless we consider it necessary... I think it is not a good idea at 
all !

**Comment by rpignolet** [comment]
If you need the Tomcat port in your component you just have to import it IMO.

**Comment by vincent-zurczak** [comment]
I do not need the Tomcat port. And I only want the port of the Tomcat I am deployed on.
The Tomcat port is the deployment context.

And we do not need the whole graph.
We only need information about where we are deployed. EJB, OSGi bundles, JBI and Fractal components all have access to a context.

Now, what is the interest of having the Tomcat port as a graph variable if we cannot change it.
Let's consider the following graph.

```
Tomcat {
     exports: ip, port = 8080;
     children: webapp;
}

webapp {
     # ...
}
```

If we specify the Tomcat port in the graph, it implies we could change it. What happened if I change the port to 8081 in the graph. Well, if the recipe is written correctly, it should inject the port in the Tomcat configuration. If it does not, then there is no interest in exporting the port as a Roboconf variable. Because otherwise, Roboconf can declare a port while Tomcat is running on another one.

Now, what about the recipe of the web application?
How to reload it if it hard-codes the port? Once again, changing the port in the graph will result in an invalid recipe. So, injecting parents variables in recipes is worth IMO. Otherwise, we should definitely stop exporting the port for servers and so on.

**Comment by vincent-zurczak** [comment]
OK. We do not have enough experience with reusability to determine whether this is necessary or not. We will delay this issue to another milestone.

**Comment by cdeneux** [comment]
I'm interested by this feature for our Petals Virtual Container (Petals in the cloud).

To deploy Petals component I have a graph similar to the following one, and to deploy a JBI component I need to know attributes (as JMX port) of the Petals container, **its ancestor**:

    PetalsContainer-VM {
        installer: target;
	    children: PetalsContainer;
    }

    PetalsContainer {
        installer: script;
	    exports: containerId = sample-0, ip, jmxPort = 7700;
	    imports: PetalsRegistry.ip, PetalsRegistry.port, PetalsRegistry.credentialsGroup, PetalsRegistry.credentialsPassword;
	    children: PetalsJBIComponent;
    }

    PetalsJBIComponent {
        installer: script;
        exports: componentId = my-component-id;
    }

**Comment by vincent-zurczak** [comment]
> Do we *really* need that ? And if so... is it only limited to ancestors ? (I mean, I don't need to be deployed in a Tomcat to require the Tomcat's port ??)

If you run on the same machine, we can consider that you can access information from your ancestors. I don't think we should give access to the whole agent's data. So, I will not even mention the whole graph's data. But giving the context of the ancestors makes sense as there are real use cases where it helps.

Getting the Tomcat port (not all the Tomcat ports!) makes sense.
Getting the Tomcat's URL suffix makes sense. The difference between a container information and an imported variable is that you know the information you have is local, while others may come from other instances, not on the same VM.

I suggest we focus on the script plug-in.
We could inject ancestors variables with *ANCESTOR*\_`component name`\_`variable name`. There is no cardinality here. We can only use ancestors' exported variables.
