### ISSUE TITLE
Move the Roboconf Maven plugin in the platform Git repo

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#208]
Yesterday, Roboconf 0.2 was released.
The release process took a little more than 2 hours.

Between the Maven releases, some manual tags, updating the web site...
After thinking about it, there is (among many things) something simple we could do to speed up releases. The Roboconf Maven plug-in is for the moment hosted in another Git repository. It was separated from the platform at the beginning because it seemed like a good idea, in particular for maintenance releases. However, knowing how it works, we could seriously move it under the **miscellaneous** directory in the platform. Its code is quite simple and it perfectly fits with the regular Maven process.

This would save between 5 and 10 minutes in the release process and remove one step from [this page](http://roboconf.net/en/developer-guide/release-management.html). It would result in an additional Maven module in the platform. We would keep the current Git repository of the Maven plugin for archives (we now have a release, we should keep the sources and tag). The readme would simply indicate the module was moved to the platform.

So, please vote to indicate if you agree with this move or not. @roboconf/developers 
Use...

* :+1:  <code>:<span>+1</span>:</code> if you agree.
* :-1:  <code>:<span>-1</span>:</code> if you disagree.
* :8ball:  <code>:<span>8ball</span>:</code> if you have no idea.

**Comment by vincent-zurczak** [comment]
:+1:

**Comment by bourretp** [comment]
While I really know nothing (yet) about the difficulty of the release process...
:+1: +1

**Comment by vincent-zurczak** [comment]
Only 2 votes until now.

**Comment by rpignolet** [comment]
:+1: 
`mvn deploy` is not for this purpose ?

**Comment by vincent-zurczak** [comment]
Nope. And it is **mvn release**...
What takes time is the [TODO list](http://roboconf.net/en/developer-guide/release-management.html) for a release. :wink:

**Comment by vincent-zurczak** [comment]
This vote will be completed on Wednesday. Any objection?

**Comment by vincent-zurczak** [comment]
OK, with 2 votes for, 0 against and 0 with no opinion, the vote is approved.
The issue will be closed as soon as the move is performed.
