### ISSUE TITLE
Bug while sending user-data related to port of message server

### ISSUE THREAD

**Issue by linkbutler** [roboconf/roboconf-platform#213]
A strange back slash "\" inserted unintentionally into the configuration sent from the DM to an agent: messaging.ip=104.40.129.163\\:5672
Result in the agent cannot understand about the messaging server.

**Comment by vincent-zurczak** [comment]
Messaging parsing should escape backslahes.
AWS's user data indeed escapes the colon.

**Comment by vincent-zurczak** [comment]
The problem is that we use Base64 to encode user data, but the agent does not decode the Base64 encoding before parsing the properties.

**Comment by vincent-zurczak** [comment]
It seems AWS replace every occurrence of **:** with **\:**, even in passwords and so on.
So, we should simply replace every read field.
