### ISSUE TITLE
Specification for reusables recipes

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#237]
This issue is about commeting and improving the specification available on the wiki and about [reusable recipes](https://github.com/roboconf/roboconf-platform/wiki/Reusable-Recipes).

**Comment by vincent-zurczak** [comment]
@everyone @ykouki @rpignolet I have completed the first draft. Thanks for reading and commenting it.

**Comment by rpignolet** [comment]
Awesome ! For me it is good and I like the "we need one Git repository by recipe" with a central repo :)

**Comment by vincent-zurczak** [comment]
After some discussions and comparisons, I indeed changed my mind about the number of repositories, although I do not like the idea of having dozens or hundreds ( :volcano: ) of Git repositories.

**Comment by vincent-zurczak** [comment]
OK all. Last day to comment the specification.
