### ISSUE TITLE
Simplify the Puppet parameters

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#241]
I have just tried to build the Open-PaaS application with the last Maven plugin (0.3-SNAPSHOT). Following this update #191, it seems some components are missing update parameters in their Puppet module. Apache, Redis and Mongo do not have the *importAdded*, *importRemoved* and *importComponent* passed by the Puppet extension during the update phase.

I completed the Puppet modules for this, but that's a lot of parameters.
I wonder whether we could not improve this. Given that Roboconf 0.3 will be released by the end of March, and since it should be the first version with efforts to build a community (with recipes repositories), I think we can break compatibility with the version 0.2. It is better to do it right now than later.

Instead of expecting these 3 parameters, we could have only one called **importDiff**. This parameter would be a map. It could contain **added**, **removed** and **component** sub-keys. That would make only one parameter to have in Puppet modules. And if for some reasons, we had to add a sub-key, that would not impact existing modules.

WDT? @ykouki @rpignolet @roboconf/developers

**Comment by rpignolet** [comment]
Why not, but we must ensure that `create_resources` will still working after the modification because it is the only way I found to loop over a hash easily.

**Comment by vincent-zurczak** [comment]
You would have spoken Chinese, that would have been the same to me. :whale: 
I read https://docs.puppetlabs.com/references/latest/function.html but that does not help me a lot. But basically, if it worked with the parameters generated from Roboconf imports, I guess that should work with the **importDiff** parameter.

**Comment by rpignolet** [comment]
For now I used the function like that:
```
create_resources(functionHandler, $importAdded)
```

But maybe we can do something like

```
create_resources(functionHandler, $importDiff['importAdded'])
```

**Comment by vincent-zurczak** [comment]
OK. We have just discussed it with Pierre-Yves.
Do you think it would be better to keep the three additional parameters called **importAdded**, **importRemoved** and **importComponent**? That makes quite a lot of parameters to add in the Puppet module definition. But it seems it would be easier to keep it this way.

**Comment by rpignolet** [comment]
It is better to keep if we can't use `create_resources` with the new single variable. This need some test to be sure. From https://docs.puppetlabs.com/puppet/latest/reference/lang_datatypes.html#hashes it seems that we just have to do `$importDiff[importAdded]` to get the value with a key so maybe it can works.

**Comment by vincent-zurczak** [comment]
OK.
But from a user's point of view, what is the most simple? Keep it like it's done today, or (if it works), merge update data into a single variable?

**Comment by rpignolet** [comment]
Ah I have an idea with what you said: if all variables in a puppet script will be wrap into a hash for example:
```
class mongo_roboconf_module($ip, $port, $importAdded) {
    // use variables
}
```
Become:
```
class mongo_roboconf_module($vars) {
    $ip = $vars[ip]
    $port = $vars[port]
    $importAdded = $vars[importAdded]
    // use variables
}
```

With this you can avoid to put useless variables in script that don't use it.

**Comment by vincent-zurczak** [comment]
Actually, I like the idea of having imported variables as parameters in the module.
In case of error, it is easy to detect what is missing. We also added automatic validation about this.

The hash idea seemed more useful for the update parameters, that are only passed during the Roboconf **update** phase.

**Comment by rpignolet** [comment]
I don't understand your point about "in case of error, it is easy to detect what is missing". If you had an export in the graph and you only use it in the start script for example, you will not miss it because you need it for the script. For me it is boring to add the added export in all scripts even if they don't need it.

I don't know if you understand my point of view.

Moreover it is the actual behavior for bash scripts, if you don't use an export variable so don't use it. With bash installer, adding an export variables does'nt require to update all scripts.

**Comment by vincent-zurczak** [comment]
```
my_module( ip, port )
```

By putting this declaration, we can detect incoherence with the graph only by validating the Roboonf application. We do not need to go to the execution to see we have an error. This is useful also because this is generally executed on the agent's side (which generally implies an SSH connection to the remote host, followed by log scrutinizing). So, the more thing we detect, the better it is.

This is why I would like to keep imported variables as module parameters.
Now, let's go back to the **importDiff**. This wraps information we only inject in the **update** phase. If the imported variables designate the current state, the importDiff contains a *diff*, i.e. what has changed since the previous invocation.

If you do not have an **update.pp**, then the **init.pp** will be invoked. And so, to retrieve this information, it should have this parameter. Today, we do not have this parameter, we have 3: importAdded, importRemoved and importComponent. The idea of this issue was to merging these 3 parameters under a single one.

**Comment by rpignolet** [comment]
So to answer to the question, I am ok to reduce diff variables into one `$importDiff`. :+1:

**Comment by vincent-zurczak** [comment]
Cool. 
You suggested another thing. It was about wrapping the component's exported variables and imports groups into the hash as well. I do not know whether this is a good thing or not. Maybe others will react.
