### ISSUE TITLE
Can't remove application in DM web console after stopping RabbitMQ

### ISSUE THREAD

**Issue by gibello** [roboconf/roboconf-platform#286]
Scenario: in the DM web console, upload an application zip. Then, stop the RabbitMQ messaging, and try to delete the application from the web console: it does nothing.

**Comment by vincent-zurczak** [comment]
In the manager, move...

```java
this.appNameToManagedApplication.remove( applicationName );
```

... right before the call to the messaging client (i.e. one line above).
Can you try and test it?

**Comment by gibello** [comment]
Le 31/03/2015 15:02, Vincent Zurczak a écrit :
>
> In the manager, move...
>
> this.appNameToManagedApplication.remove( applicationName );
>
> ... right before the call to the messaging client (i.e. one line above).
> Can you try and test it?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/roboconf/roboconf-platform/issues/286#issuecomment-88075320>.
>
Does not seem to change anything.

**Comment by vincent-zurczak** [comment]
OK. Then, go ahead and wrap all the messaging stuff in the method with catch blocks.

```java
try {
      messagingClient.doSomething();

} catch( IOException e ) {
     Utils.logException (e );
}
```

**Comment by vincent-zurczak** [comment]
I think you can group all the messaging calls inside the try block. Deleting messaging artifacts does not have to be made at the end.

**Comment by gibello** [comment]
Le 31/03/2015 16:09, Vincent Zurczak a écrit :
>
> I think you can group all the messaging calls inside the try block. 
> Deleting messaging artifacts does not have to be made at the end.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/roboconf/roboconf-platform/issues/286#issuecomment-88101647>.
>
Also, there is a checkConfiguration() method called at the beginning of 
deleteApplication( ...), that throws an exception if the messaging 
config is not operational.

Enclosing everything into try/catch blocks makes this check useless 
(because I would have to try/catch it as well... which has no meaning at 
all).

**Comment by vincent-zurczak** [comment]
What really matters when we delete an application is the fact that all the instances are not deployed.
So, you can forget about the try/catch.

Just move the checkConfiguration and messaging operations at the end of the method.

**Comment by gibello** [comment]
Le 31/03/2015 16:16, Vincent Zurczak a écrit :
>
> What really matters when we delete an application is the fact that all 
> the instances are not deployed.
> So, you can forget about the try/catch.
>
> Just move the checkConfiguration and messaging operations at the end 
> of the method.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/roboconf/roboconf-platform/issues/286#issuecomment-88103936>.
>
All this stuff does not solve anything (even adding try/catch and 
ignoring everything), because I get errors further (seems to be when 
trying to close the connection), that cause the web service to fail - 
and the application console does not remove the application.

**Comment by vincent-zurczak** [comment]
You will get an error in the REST API if the deleteApplication method throws an exception.

**Comment by vincent-zurczak** [comment]
Oops! I did not want to close this issue (not yet!).

**Comment by vincent-zurczak** [comment]
OK. It was due to a runtime exception...
