### ISSUE TITLE
Swich compilation level to 1.7

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#292]
Currently, Roboconf projects are compiled with the Java 1.6 level.
However, we do not build it anymore against Java 1.6 (Oracle and OpenJDK). This is because some of the libraries we rely on do not support it anymore (PAX, etc).

Besides, we also talked about it with @bourretp on Monday.
And after thinking about it, why not. So, here is a vote to change it. Express your opinion.

As a reminder, use...

* :+1:  <code>:<span>+1</span>:</code> if you agree.
* :-1:  <code>:<span>-1</span>:</code> if you disagree.
* :8ball:  <code>:<span>8ball</span>:</code> if you don't care.

**Comment by vincent-zurczak** [comment]
:+1: for me.
That would allow us to use multiple catch. That could save some lines of code and improve code coverage with few efforts. See http://docs.oracle.com/javase/7/docs/technotes/guides/language/catch-multiple.html

Besides, it does not prevent people from coding in Java 1.6 mode if they want.

**Comment by rpignolet** [comment]
:+1:

**Comment by GrahamLinagora** [comment]
:+1:

**Comment by bourretp** [comment]
:+1: for java 1.7
+ another :+1: to jump directly to java 1.8, but that's another vote, isn't it? ;)
λ power!

**Comment by vincent-zurczak** [comment]
Tomorrow afternoon, I will close this vote.

**Comment by vincent-zurczak** [comment]
Vote approved. I pushed the modification along with my last pull request.
