### ISSUE TITLE
Unexplained error generated by the roboconf-maven-plugin

### ISSUE THREAD

**Issue by cdeneux** [roboconf/roboconf-platform#300]
Hi all,

When compiling my Roboconf project (https://github.com/petalslink/petals-virtual-container, commit [b423b18](https://github.com/petalslink/petals-virtual-container/commit/b423b181be1a884ebdd3d371954b92a5302609d7)) with maven, I get the following unexplained error:
    [INFO] --- roboconf-maven-plugin:0.2:validate-application (default-validate-application) @ petals-pvc ---
    [INFO] Generating a report for validation errors under target/roboconf/roboconf-validation.txt
    [ERROR] [ parsing ] Invalid content. A property or an instance was expected.
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------

Can you add more explanation on this error to find its cause ?

Regards,

**Comment by vincent-zurczak** [comment]
Replace...

```member-id = registry-node-1;```

... by...

```member-id: registry-node-1;```

But indeed, the error message is not clear enough.
Something like **Invalid syntax. ...**. The error details are generally outputed under **target/roboconf**. In this case, it seems that no line number is written in the details. So, we should also add a line number.

Eventually, the Maven plugin should indicate more details are available under **target/roboconf**.

**Comment by rpignolet** [comment]
@vincent-zurczak you do not specify the file :wink: 
The errors are in the file: `src/main/model/instances/model.instances`

**Comment by vincent-zurczak** [comment]
You are right, thanks. :smiling_imp:

**Comment by vincent-zurczak** [comment]
The error message was changed to **Syntax error: a property or an instance was expected.**.
The error line is also set now.
