### ISSUE TITLE
Templating language produces tons of line breaks

### ISSUE THREAD

**Issue by gibello** [roboconf/roboconf-platform#304]
Every statement in a template results in a line break (= a blank line in the generated report).
The only way to prevent it is putting all the code on a single line, when possible...
We can't envisage to do that automatically, because sometimes we *really* need to produce a line break !
If no easy solution can be found... maybe we could provide a "linebreak" statement, then automatically compress the code before expanding the template ?

**Comment by vincent-zurczak** [comment]
I fixed it. There was an option for that in Handlebars.
