### ISSUE TITLE
Templating: specify destination file for a report

### ISSUE THREAD

**Issue by gibello** [roboconf/roboconf-platform#306]
Generated resources are in $ROBOCONF_ROOT/generated or $ROBOCONF_ROOT/generated/app-name, and the report is named against the template name (eg. "myreport.tpl" will generated a report called "myreport"). This is hard-wired.
It should be possible to specify where the report should be generated (directory + file name).

**Comment by vincent-zurczak** [comment]
Is this really Roboconf's job to put generated resources at some location?
Most likely, this can result in permissions issues. IMO, Roboconf should put the generated resources all in the same place.

Then, it is up to the client (client meaning human or program) to pick up these files in the right location. Setting permissions on a single directory is easier than doing it on N directories. If a program needs a file in another location, it is up to it (or an associated extension) to move it.

If you agree, I would like to close this issue.

**Comment by vincent-zurczak** [comment]
Let's make things simple.
Comments in Mustache follow this convention: `{{! ignore me }}`. So, we could allow the definition of meta-tags as comments. We read template contents. So, parsing them is not a big deal.
