### ISSUE TITLE
Add a REST operation to upload images

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#308]
Users should be able to upload images for their applications or their applications templates.

**Comment by vincent-zurczak** [comment]
See JCrop.
http://deepliquid.com/projects/Jcrop/demos.php?demo=thumbnail

The REST operation must take an input stream and new boundaries (the crop operation should be done on the server side since only latest browsers support it on the client side).

**Comment by bourretp** [comment]
Re-opening: images are uploaded to the wrong location!
Fix should be quick
