### ISSUE TITLE
Add support for Docker Files

### ISSUE THREAD

**Issue by cdeneux** [roboconf/roboconf-platform#310]
Roboconf supports Docker but we can't use docker files to define the content of the docker container.

Please, add something to support docker files.

**Comment by vincent-zurczak** [comment]
You may be interested by #479, as both options may reunite.

**Comment by vincent-zurczak** [comment]
#479 is one thing.
But now that we have Docker images on Docker hub, we should rely on them and rewrite a part of our Docker target extension. In fact, we should replace ALL the properties related to image generation and allow to specify a Docker file instead. This Docker file would extend our official agent image. The web site would provide some examples.
