### ISSUE TITLE
Create a room on gitter.im

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#311]
https://gitter.im is an instant messaging service for Github projects.
It means no registration is required, we can login with our Github account. Besides, no need of installing any application, a web browser is enough.

We already have Github issues that can counter-balance the lack of mailing-lists. However, if we refer to our commits and our tweets, Roboconf does not appear like a **very active** project. We have difficulties to promote our ongoing work.

I think having such a public room could ease contacts and discussions, even within the team.
We could also use it to publish summaries of our weekly meetings, rather than sending them by e-mail.

Let's vote!
Who agrees about the creation of an IM room for Roboconf?

**Comment by vincent-zurczak** [comment]
:+1:

**Comment by bourretp** [comment]
:+1:

**Comment by vincent-zurczak** [comment]
@roboconf/developers @roboconf/owners For those who did not receive a notification, there is an ongoing vote about creating a public discussion channel for Roboconf.

**Comment by rpignolet** [comment]
:+1:

**Comment by GrahamLinagora** [comment]
:+1:

**Comment by vincent-zurczak** [comment]
Done: https://gitter.im/roboconf/roboconf
I will add links on the web site.
