### ISSUE TITLE
About component reusability

### ISSUE THREAD

**Issue by cdeneux** [roboconf/roboconf-platform#314]
The keyword "extends" in the graph can be used to define pseudo inherited components to avoid to duplicate some properties, scripts, ...

If our inherited components must have little different deployments or startups, it is required to use Maven to put the right scripts in the right directory of the Roboconf archive generated by the roboconf-maven-plugin. This is not very agile because if the Roboconf archive format changes we must review our POM file to adapt changes. It should be better to introduce a inheritance policy about scripts.

Such a policy could be the following one:
- scripts "deploy, start, stop, undeploy" must be defined in the base component,
- these scripts will execute sub-scripts for each parts that are differents for each inherited components
- these sub-scripts are defined in the inherited components
- the roboconf-maven-plugin will automatically duplicate scripts "deploy, start, stop, undeploy" in inherited component directories
- the roboconf-maven-plugin will automatically embed sub-scripts in their own inherited component directory

**Comment by vincent-zurczak** [comment]
Question: how do you deal with multiple inheritance?
Component A extends component B which extends component C...

Why put restrictions on the files (**deploy.sh**, etc)?
Bash is not the only plugin. This should also apply to Puppet. So, we should rather stick with this policy:

1. Find the upper component in the inheritance hierarchy. List all its files.
2. Process the same way with extending components. Override the upper list with the provided files.
3. Etc.

To prevent a sub-component from including an inherited file, we could put in the component's directory a **.roboconf.excludes** file that would list the inherited files that should not be considered for this component.

**Comment by cdeneux** [comment]
I think that you should deal the multiple inheritance in the same way: sub-scripts of the component B will execute sub-sub-scripts of the component A ;)

Perhaps, the default inheritance policies should be defined plugin per plugin. The default inheritance policy for script can ba have no sens for Puppet plugin ?

I'm not sure that an exclusion mechanism is needed. The model base on script/sub-script is the same that an object model where all methods are declared final (extension points are declared as abstract methods).

**Comment by vincent-zurczak** [comment]
Well, you proposed something that matches your use case.
But given the script plugin, we could also imagine a user only wants to override a properties file in a sub-component, rather than rewriting a script file.

Let's give use some time to think about it. :+1:

**Comment by vincent-zurczak** [comment]
This is just an upgrade of the Roboconf Maven plugin.
But it only applies to the script plug-in. IMO, this can easily be achieved with another Maven plug-in (e.g. ANT), for those who need it.
