### ISSUE TITLE
Use arrays in scripts

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#319]
Currently, the script plugin generates environment variable names and insert indexes.
Example: tomcat_0_ip, tomcat_1_ip...

It is quite painful to iterate over such variables.
It would be better to try to use arrays. It seems recent bash versions support them.

To investigate.  :microscope:

**Comment by gibello** [comment]
Le 03/06/2015 11:19, Vincent Zurczak a écrit :
>
> Currently, the script plugin generates environment variable names and 
> insert indexes.
> Example: tomcat_0_ip, tomcat_1_ip...
>
> It is quite painful to iterate over such variables.
> It would be better to try to use arrays. It seems recent bash versions 
> support them.
>
> To investigate. :microscope:
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/roboconf/roboconf-platform/issues/319>.
>

Painful ? bash example follows...

for (( c=0; c<$Tomcat_size; c++ ))
do
  IP_ADDRESS=Tomcat_${c}_ip
  echo $IP_ADDRESS
done

With such a loop, we might if necessary fill in an array...

Not sure it is painful enough so we support only recent versions of bash 
(the script plugin is not just a "recent bash" plugin, but also supports 
sh - and should be compatible with other tools like perl, etc...)

**Comment by vincent-zurczak** [comment]
Indeed.
I missed this in the documentation, but it is written.

**Comment by gibello** [comment]
Le 03/06/2015 11:36, Vincent Zurczak a écrit :
>
> Indeed.
> I missed this in the documentation, but it is written.
>
Because I just updated the doc :)
What was missing is documentation, indeed...
