### ISSUE TITLE
Incoherent import management in the agent

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#345]
Follow this scenario:

1. Deploy and start a component with optional dependencies.
2. Make sure the optional dependencies are deployed and started.
3. Undeploy the component.
4. Deploy and start it again.

What happens?
At the second step, the component will have its dependencies (even if they are optional, it will be notified about their presence). But at the fourth step, no dependency will be visible. Why?

Actually, here is how it works: when we **ADD** an instance in the agent's model, we request exports from other agents. And so, we will update our imports. When we **undeploy** a component, we clear the imports. And we do **NOT** request exports anymore, **unless** the dependencies are required.

This is clearly a bug.
There are two solutions:

* We can stop clearing the imports when we undeploy a component.
* Or we can request imports when we deploy a component, in addition to when we add it in the model.

Notice that during the whole life time of an instance, we listen to exports from other agents.
So, even an undeployed instance will be notified when its dependencies change. So, I'd rather choose to not clear the imports anymore.

On the other hand, clearing the imports has the advantage of removing ghost imports (i.e. dependencies that were removed but whose notifications vanished or were lost). For this use case, requesting exports during the deploy operation is more powerful.

Notice also that this problem did not occur with required dependencies.
This is because the start operation is blocking and will require exports from other agents if dependencies are missing.

**Comment by vincent-zurczak** [comment]
I'd rather take the option 1, stop removing imports.
This is more coherent since we keep on listening to export changes.

For the "hard reset" use case, I think we should rework the "synchronize" message.

**Comment by rpignolet** [comment]
Found this issue when I add a component with optional imports and I played with the start, stop and undeployed button :smile:

**Comment by vincent-zurczak** [comment]
Done, with solution 1.
The "hard reset" use case will be addressed in #347.
