### ISSUE TITLE
Check the base image exists before creating an image (Docker)

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#346]
Following the bug reported in #334, Roboconf should verify the base image is in the local repository before trying to create an image.

**Comment by cdeneux** [comment]
If the base image does not exist in the local repository, Roboconf should try to download it from official docker registry, except if another remote Docker registry is set through the new property `docker.image.registry`.
This property could be used also to retrieve the image defined by `docker.image` to avoid a generation if it was deployed previously on a Docker registry.

**Comment by vincent-zurczak** [comment]
I don't know if it is a good idea that Roboconf downloads the image.
Sure, it is feasible. But on the other hand, every Robocon f deployment requires a little preparation. And verifying a base image is here is not hard at all with Docker CLI.

I am not sure it is worth it.
Then, given our schedule, this issue will only be about verification. For downloading, please create another issue, as we won't discuss and implement it for this week's release.

**Comment by cdeneux** [comment]
In a system operator point of view, the Docker image downloads will simplify their use of Roboconf. Why the system operator should pulled manually the Docker image required by the Roboconf application that he is deploying ?

Associate issue: #348

**Comment by vincent-zurczak** [comment]
OK. This will be dealt with in #348. :smiling_imp:
