### ISSUE TITLE
Invalid Agent installation in Docker if we use a SNAPSHOT version

### ISSUE THREAD

**Issue by cdeneux** [roboconf/roboconf-platform#351]
I try to generate a Docker VM with the Roboconf agent version 0.4-SNAPSHOT. So I use the value `https://oss.sonatype.org/content/repositories/snapshots/net/roboconf/roboconf-karaf-dist-agent/0.4-SNAPSHOT/roboconf-karaf-dist-agent-0.4-20150624.172802-8.tar.gz` for the parameter `docker.agent.package`.

I think the Docker image is not correctly created, `/usr/local/` contains following directories:
  * `roboconf-agent` a symlink on `/usr/local/roboconf-karaf-dist-agent-0.4-20150624.172802-8`
  * `roboconf-karaf-dist-agent-0.4-20150624.172802-8`
    * `start.sh`
  * `roboconf-karaf-dist-agent-0.4-20150624.172802-8.tar.gz`
  * `roboconf-karaf-dist-agent-0.4-SNAPSHOT`
    * `bin`, `etc`, ...

In my mind, `roboconf-agent` should be a symlink on `/usr/local/roboconf-karaf-dist-agent-0.4-SNAPSHOT` because `roboconf-karaf-dist-agent-0.4-SNAPSHOT` is the root directory of the archive `roboconf-karaf-dist-agent-0.4-20150624.172802-8.tar.gz`.

**Comment by vincent-zurczak** [comment]
Indeed, it is assumed the directory name is the name of the archive, which is not the case here.

**Comment by vincent-zurczak** [comment]
OK. I updated the way we deal with archives.
I tested deployments with the following **target.properties** files.

```properties
# Local snapshot
target.id = docker
docker.image = demo_roboconf_0.4_snapshot
docker.option.cap-add = SYS_PTRACE
docker.agent.package = file:/home/vzurczak/.m2/repository/net/roboconf/roboconf-karaf-dist-agent/0.4-SNAPSHOT/roboconf-karaf-dist-agent-0.4-SNAPSHOT.tar.gz
```

```properties
# Remote snapshot
target.id = docker
docker.image = demo_roboconf_0.4_snapshot
docker.option.cap-add = SYS_PTRACE
docker.agent.package = https://oss.sonatype.org/content/repositories/snapshots/net/roboconf/roboconf-karaf-dist-agent/0.4-SNAPSHOT/roboconf-karaf-dist-agent-0.4-20150624.172802-8.tar.gz
```

```properties
# Remote (dynamic) snapshot
target.id = docker
docker.image = demo_roboconf_0.4_snapshot
docker.option.cap-add = SYS_PTRACE
docker.agent.package = https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=net.roboconf&a=roboconf-karaf-dist-agent&v=0.4-SNAPSHOT&p=zip
```

```properties
# Released version
target.id = docker
docker.image = demo_roboconf_0.4_snapshot
docker.option.cap-add = SYS_PTRACE
docker.agent.package = http://repo1.maven.org/maven2/net/roboconf/roboconf-karaf-dist-agent/0.3/roboconf-karaf-dist-agent-0.3.tar.gz
```

Extraction and image creation worked correctly for all of them.
Only the last test could not be pushed farther, since launch parameters are not the same in versions 0.4 and 0.3. But the failure reported in this issue was about the creation of the image, and this is now fixed for snapshots versions.

**Comment by cdeneux** [comment]
That works fine with my test with the last 0.4-SNAPSHOT (#9)
