### ISSUE TITLE
Deployment blocked if no JVM is installed in a Docker container

### ISSUE THREAD

**Issue by cdeneux** [roboconf/roboconf-platform#367]
I use the Docker target option `docker.agent.jre-packages` to add packages missing to the base image `ubuntu:15.04`:

    docker.agent.jre-packages = vim net-tools

With this option value, the deployment of the Docker container is blocked, no error appears on DM side or on agent side.

The problem is due to the missing JRE: if no JRE is specified by `docker.agent.jre-packages`, no JRE will be installed in the Docker container, and so the agent start-up fails. This error seems to be not propagated to the DM, and my application deployment is blocked on `being deployed`.

**Comment by bourretp** [comment]
I see two things here:
- Overriding the docker packages without specifying a JRE, which, in my opinion, is an user error.
- The silent agent failure, without any notification to the DM, is indeed a bug. I'm looking into it.

For the first point, I would suggest to add a property that could be use to add additional packages, without overwriting the predefined ones. Maybe something like `docker.agent.packages.additional`. In your case:
```
docker.agent.packages.additional = vim net-tools
```
will result in the following packages to be installed:
```
unzip* openjdk-7-jre-headless vim net-tools
```
\* only if using the zipped agent archive.

WDYT?

**Comment by cdeneux** [comment]
I'm not sure it is a user error because generating your own Docker image avoid to download several times the same packages available on public repositories.
You can view this image generation as a new step in Roboconf life cycle previous to the step "deploy". So Roboconf will automatize completely the deployment: production operators needs only to configure Roboconf and deploy Roboconf applications coming from development teams without any other manual operations.
I'm my mind the image generation should be available on other IaaS as UShareSoft can do, and Roboconf will become a serious competitor.

As package are not relative to the agent, I think that the new properties should be named as 'docker.additional.packages'.

**Comment by gibello** [comment]
Le 06/07/2015 16:26, Pierre Bourret a écrit :
>
> I see two things here:
>
>   * Overriding the docker packages without specifying a JRE, which, in
>     my opinion, is an user error.
>
It is. This property was introduced to override the default JRE package 
(I just found useful to support additional ones, if any !)

So, if you mean we need 2 properties (one for "alternate JRE", the other 
for "additional package"), why not. It adds some complexity, but may 
limit user errors.

||||||||
>
>   * The silent agent failure, without any notification to the DM, is
>     indeed a bug. I'm looking into it.
>
The agent can't be launched without a JVM, so there won't be any notif. 
The DM must detect the problem by itself.

**Comment by vincent-zurczak** [comment]
> The agent can't be launched without a JVM, so there won't be any notif. The DM must detect the problem by itself.

Indeed.
I suspect there is an error message in the Docker run's output. Something indicating that the **start.sh** failed. By checking the output, we could throw a **TargetException** when **start.sh** does not execute succesfully.

**Comment by bourretp** [comment]
Issue split into:
- a bug : #389 
- an improvement : #390

**Comment by bourretp** [comment]
#390 has been fixed. The container startup error detection (#389) is a bit more complicated, but the underlying reason (no java) can be easily avoided using the `docker.additional.packages` property.

Doc has been updated: http://roboconf.net/en/user-guide/target-docker.html

Feel free to close this issue if it seems fixed to you.
