### ISSUE TITLE
Verify all the Javadoc comments

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#371]
During the release for Roboconf 0.4, we encountered issues due to invalid Javadoc comments.
Even if we skip this kind of validation in releases now, we should verify the correctness of our Javadoc.

We can use [mvn javadoc:javadoc](https://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html) or [mvn javadoc:fix](https://maven.apache.org/plugins/maven-javadoc-plugin/fix-mojo.html) to achieve this. Relying on the Javadoc profile in Roboconf (**jdoc-and-sources**) seems useless IMO.

**Comment by vincent-zurczak** [comment]
I finally used ` mvn clean package -P jdoc-and-sources -rf :roboconf-core -DskipTests=true | grep WARNING > javadoc.txt` to gather all the warnings related to Javadoc. Notice that this does not prevent the Java 8 linter to fail with the code. But some rules are just too restrictive.

Anyway, the upcoming commit fixes the warnings and errors that were in our Javadoc.

**Comment by bourretp** [comment]
Ok, so I think this issue may be closed as soon as PR is merged.
BUT: before we can use auto javadoc check in travis (using the roboconf.javadoc.check property), the roboconf-parent-1.5 must be released.

**Comment by vincent-zurczak** [comment]
Can you perform the release please?

**Comment by bourretp** [comment]
I hope I remember the process, but yes, I'll give it a try ;)

**Comment by vincent-zurczak** [comment]
At worst, the process is documented on the web site. ^^

**Comment by bourretp** [comment]
Tested & released.
Waiting for propagation to central, then bumping platform to parent 1.5.
