### ISSUE TITLE
Verify Karaf clients can connect to the DM

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#373]
* Install the DM with the Debian package.
* Try to connect to the Karaf console in interactive mode by using the client. `./client -u karaf`

Until now, we did not succeed.
Try to fix it...

**Comment by gibello** [comment]
?
Just tested on Docker (ubuntu /bin/bash), with success.
Installed as follows:
$ dpkg -i roboconf-dist-debian-dm_0.5+SNAPSHOT_all.deb
$ apt-get install -f

Then:
$ /opt/roboconf-dm/bin/client -u karaf

Got logged in (using password "karaf").

So what is the issue ? Should we just put a symlink somewhere with a better name than "client" (eg. /usr/bin/karaf-client), do nothing... or did I miss something ?

**Comment by vincent-zurczak** [comment]
We tried the other day, and it did not work.
Could you add this on the web site? Somewhere in the configuration of the DM as an example...

**Comment by vincent-zurczak** [comment]
And we installed the DM with sudo apt-get install... and not dkpg.

**Comment by gibello** [comment]
Le 06/07/2015 17:44, Vincent Zurczak a écrit :
>
> And we installed the DM with sudo apt-get install... and not dkpg.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/roboconf/roboconf-platform/issues/373#issuecomment-118902181>.
>
Right... In fact, it does not work if we use the public distro on Bintray.

My dpkg test was using... karaf 4 (because I installed the latest 
0.5-SNAPSHOT package).

So, it seems to work fine on Karaf 4, but not on Karaf 3 !

**Comment by vincent-zurczak** [comment]
And does it work with Karaf 3 and DKPG?

**Comment by gibello** [comment]
Le 07/07/2015 13:24, Vincent Zurczak a écrit :
>
> And does it work with Karaf 3 and DKPG?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/roboconf/roboconf-platform/issues/373#issuecomment-119175851>.
>
No, it does not. The package released on bintray has the same behaviour, 
it does not depend on the way we install it.

It seems related to the karaf remote (ssh) shell that does not start.

**Comment by vincent-zurczak** [comment]
OK. As 0.4 is not a *complete* version for me, I don't think it is worth finding a workaround for this. As long as it works for version 0.5. If you agree, I suggest we mark this issue as **won't fix**.

I created #383 to guarantee this work from now.
