### ISSUE TITLE
DM Jersey error: cannot find class `ResponseCorsFilter`

### ISSUE THREAD

**Issue by bourretp** [roboconf/roboconf-platform#377]
After the switch to Karaf 4, I've found the following error to occur quite often during integration tests :

`2015-07-03 14:05:43,469 | ERROR | FelixStartLevel  | ProviderServices                 | 13 - com.sun.jersey.core - 1.18.2 | The class net.roboconf.dm.rest.services.internal.cors.ResponseCorsFilter could not be found. This class is ignored.`

Despite being an error, it does not appear to impact the DM. But maybe it could prevent it to run when the webconsole and the rest services are exposed by different domains...

The error does *not* appears when running the DM "by hand".

I strongly suspect this is a classloading issue, as always with OSGI ;)

**Comment by vincent-zurczak** [comment]
Maybe because the class is in an internal package?
