### ISSUE TITLE
Add the support to create LXC containers in a IaaS VM

### ISSUE THREAD

**Issue by donsez** [roboconf/roboconf-platform#38]
LXC (https://linuxcontainers.org/) enables to isolate processes in a Linux physical or virtual machines.

Add the support to create LXC containers in a IaaS VM in order to build PaaS (such as Heroku) for hosting services written in Ruby, Node.js, Clojure, Java, Python, Scala, Erlang ...

**Comment by vincent-zurczak** [comment]
Somehow a duplicate of our Docker support.
