### ISSUE TITLE
Duplicated classes

### ISSUE THREAD

**Issue by cdeneux** [roboconf/roboconf-platform#384]
I'm writing my own Roboconf plugin for Petals.

I use 'duplicate-finder-maven-plugin' to find if some classes are duplicated in several dependencies. Following duplicates are detected:
* found duplicate (but equal) classes in [com.github.spullara.mustache.java:compiler:0.8.14, net.roboconf:roboconf-plugin-api:0.4]: `com.github.mustachejava.*`
* found duplicate (but equal) classes in [com.google.guava:guava:13.0.1, net.roboconf:roboconf-plugin-api:0.4]: `com.google.common.annotations.*`
* found duplicate (but equal) classes in [com.github.spullara.mustache.java:compiler:0.8.14, net.roboconf:roboconf-plugin-api:0.4]: `com.github.mustachejava.*`

**Comment by vincent-zurczak** [comment]
The fact is the plugin API should not include Mustache.
From memories, only Bash use it. So, we can either put it only in Bash, or create another Mustache utility bundle.
