### ISSUE TITLE
Reduce log level for some loggers

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#387]
The logging configuration for Roboconf has a global settings.
By default, we set it to **TRACE**... because we are still in development mode. However, some classes are wasting the logs with useless messages (most of the time).

I suggest we change the log level to DEBUG for the following classes:

* CheckerMessagesTask: "The messager checker task runs."
* ApplicationResource: "Request: list all instances for Cluster."
* AbstractThreadedTargetHandler: "Periodic check is running."

This will make the logs much more readable, even in debug mode.
WDYT?

**Comment by vincent-zurczak** [comment]
@roboconf/developers @roboconf/owners Time to vote! :smiling_imp:

**Comment by rpignolet** [comment]
The heartbeat message is remove ?

**Comment by vincent-zurczak** [comment]
No. This one will still be visible.
But we might add **DmMessageProcessor** to the above list.

**Comment by rpignolet** [comment]
I think you should hide periodic DM and Agent message like heartbeat. I do not know if there is other logs like this.

**Comment by rpignolet** [comment]
:+1:

**Comment by gibello** [comment]
:+1:
