### ISSUE TITLE
Docker target: docker.command.line is messed up with Roboconf agent parameters.

### ISSUE THREAD

**Issue by bourretp** [roboconf/roboconf-platform#393]
Inside tests, I run a Docker container in order to check that some packages are installed in its image.
I don't need the agent to run (and in fact, it will fail to run because its messaging configuration is ... unusual).

So I set the `docker.command.use` to `true` (because the Docker image is generated, and has no CMD instruction) and also set `docker.command.line` to `tail -f /dev/null`, so my container keeps running until I do need it anymore.

The problem is that the DockerMachineConfigurator:
1) does not split the command line, so Docker tries to run an executable called `"tail -f /dev/null"`, with the spaces...
2) append all the `agent.*` and `msg.*` properties to the command line, so even if the command line is just one word (like `yes`), it will fail because of unknown parameters.

If a command line has been provided, it seems cumbersome to append parameters it has no chance to understand. I thus suggest to append the Roboconf agent parameters only if `docker.command.line` is *not set* (and of course split the string into pieces).

WDYT?

**Comment by vincent-zurczak** [comment]
> So I set the `docker.command.use` to `true` (because the Docker image is generated, and has no CMD instruction)

Then, actually, `docker.command.use` should be set to **false**.
**true** is already the default value. Messaging parameters and so on are passed if and only if the `docker.command.use` is not set or set to true.

PS: I also change some code related to Docker in my PR #381. 
PS (bis): for such a test, I think you could create a script that checks at startup if Java is executed. This assumes that when a Docker startup script fails, Roboconf should detect it.

**Comment by bourretp** [comment]
To memory, by looking at the `DockerMachineConfigurator` (the one in the maste), if I set `docker.command.use` to false, the container is started without any command (`docker.command.line` is completly ignored).
```java
List<String> args = new ArrayList<> ();
...
if( useCommand ) {
   // Build the command by adding things to args
} // No else! so args is empty.
...
CreateContainerCmd cmd = this.dockerClient.createContainerCmd( imageId )
					.withName( containerName )
					// below: if docker.command.use=false, args is empty!!!
					.withCmd( args.toArray( new String[ args.size()])); 
```

I would happily check the expected packages are present on such a container (that's the actual point of my test). Unfortunately it does not run (or it does, but stops immediately because there is nothing to run). My point is that I should be able to run something long, or at least something else than the agent, without the agent.* and msg.* properties that will make any command fail.

**Comment by vincent-zurczak** [comment]
OK, args is empty. ;)
That's normal in the sense where it is assumed a CMD instruction will be specified in the Docker file. Look at [here](https://github.com/roboconf/roboconf-platform/blob/master/core/roboconf-target-docker/src/test/resources/image/Dockerfile) for an example... 

Disabling `docker.command.use` was clearly for tests.
And I assumed we could put whatever we wanted, directly in the Docker file.

**Comment by bourretp** [comment]
You're right too, I would have use my own Dockerfile if the thing I am testing is precisely the `DockerfileGenerator` configured with additional packages.

I have successfully patch the `DockerMachineConfigurator` to run my tests (successfully too;):
```
PSEUDO CODE:
if( docker.command.use is defined ) {
  if ( docker.command.line is empty ) {
     // We launch the agent/start.sh with all the agent & msg parameters
  } else {
    // We use the provided command line verbatim, without any additional argument.
    // (It needs to be split into tokens first)
}
```

No additional property! May I submit that change?

But there might be (some day) a case where we need to run a command *with* all the Roboconf configuration. That day we'll need another property (`docker.command.appendAgentConfiguration`?)

**Comment by vincent-zurczak** [comment]
> Inside tests, I run a Docker container in order to check that some packages are installed in its image.
> I don't need the agent to run

I assume you only want to perform tests about running Docker containers.
And maybe detect errors when we start one of them (e.g. when no JVM is here). Am I right?

I think we can avoid adding new code for that.
I think it can be more simple to...

* ... move the container creation part in **DockerUtils** (yes, it's about 3 lines of code for the moment).
* ... create a dedicated Dockerfile in the test resources.
* ... create an image and/or your container directly in tests.

I'd prefer adding code in tests rather than adding new "runtime" code just for tests.

**Comment by bourretp** [comment]
Mmmh, I think there might be confusion in the air. Maybe you should take a look at my branch [fix#367](https://github.com/bourretp/roboconf-platform/compare/master...fix/%23367), especially the test.

I test the Dockerfile generation through the `DockerTargetHandler`. The reason is:
- The target handler reads the target properties (especially `docker.additional.packages` which is the pernicious reason for all that noise), via `DockerMachineConfigurator`.
- The `DockerMachineConfigurator` handles the properties, constructs the image, creates the container and let it run...
- (just to recap previous comments): I need a running container, with a *&lt;font size="1000000"&gt;* **Roboconf generated image** (no custom Dockerfile ever!).

Apart from that:
- I find very strange that the Docker target handler allows to specify a custom command (`docker.command.line`), but this command get polluted by Roboconf agent parameters. If the property is just a way to customize the location of the agent's start.sh script, then its name is definitely wrong (should be like: `docker.agent.start.script`, or maybe something longer...). 
- The `docker.command.line` was so useful that (until I got involved :D ) it was totally unused and untested! (but still... it was documented)
- I propose to give usefulness to a poor little property that was lost & meaningless...
- Adding another property (like a switch to decide if we should append Roboconf parameters) is not that bad. I mean there already was an useless property, why not another one?
- I agree this whole issue is just about test, and adding things in the Docker handler just for tests is ... not great, BUT:
    - between testable & [detestable](http://martinfowler.com/bliki/Detestable.html), I pick the first one 
    - there are already tons of setters in iPOJO components that are just here because we want to test the component. Count the setter lines, compare with the changed lines of my proposal (and don't forget most of my changes are just re-indentation ;)
    - maybe the most "important" thing ever: *coverage will increase* :fireworks: 
    - downside: unit tests of the Docker handler are long, very long (≃ +1min30 on my machine, multiply by 10³ on Travis)

**Comment by vincent-zurczak** [comment]
Hi! :smile: 

>  need a running container, with a **Roboconf generated image**

All right.
This reminder was not useless.

>  unit tests of the Docker handler are long, very long

Unit tests that create Docker containers are not run on Travis.
Or at least, there were not on the previous Travis infrastructure.

> `docker.agent.start.script`...

We already have... `docker.command.line`, `docker.command.use`. And you want to add a new one, that will parse arguments too. Maybe we could do more simple.

We could have one option, called `docker.run.exec`, that matches Docker's RUN command, and that would be an array of strings. By default, the value would be `[ "/usr/local/roboconf-agent/start.sh", "$msgConfig$", "$applicationName$", "$instancePath$", "$messagingType$" ]`.

1. This way, we natively support arrays of commands. No need to parse it (or almost).
2. We can decide if we should pass arguments to the RUN command or if we should pick it up from the Dockerfile (set a blank value to use the Dockerfile RUN command).
3. When creating an image by hand, we can customize the launch script and the parameters that will be injected.
4. You will be able to run your unit tests.
5. This option is used for tests and for use cases.
6. One option is more readable than 50 other ones (at least, for someone who knows the RUN syntax in a Dockerfile).

What do you think about it?

**Comment by bourretp** [comment]
:+1:
I start to implement that right now!

**Comment by vincent-zurczak** [comment]
Great.  :smiling_imp:

**Comment by bourretp** [comment]
Tech note:
The solution mentioned above would imply to change the signature of a lot of methods from `Map<String,String> targetProperties` to `Map<String,Object> targetProperties`... While the is possible, I propose to keep a string-valued map, and to use the following syntax:
```properties
docker.run.exec.0 = command
docker.run.exec.1 = arg1
docker.run.exec.2 = arg2
...
```

It has main advantage of being serializable in a properties file. Or we can use a string & array syntax *à la* JSON...
```properties
docker.run.exec = ["command", "arg1", ... ]
```

Elegant, but a bit more complicated...
WDYT?

**Comment by vincent-zurczak** [comment]
I don't see where it would change a lot of things.
The machine configurator receives a map of string-string. And the key **docker.run.exec** has a complex value that needs to be *parsed* (a single line with regex replacements).

If you take my example above, it was already a JSon syntax, just like in the Dockerfile.
So, solution 2. ;) It impacts only one thing: the way we run a new Docker container.
