### ISSUE TITLE
[Docker] Agent extra-deployments should be separated by colons...

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#399]
... and not by spaces. :)

**Comment by bourretp** [comment]
Colons (`:`) are used as separator between an URI scheme and its scheme-specific-part.
I think you mean comma (`,`), or maybe semicolon (`;`).

BUT (yes, there always is a 'but') both comma and semicolon are allowed characters in a URI (and URLs). Spaces are *not*.

**Comment by vincent-zurczak** [comment]
I was indeed thinking to commas. :+1:  :dart: 
Commas are indeed allowed in URLs, but writing spaces in properties files can be tricky, in particular when we break values across several lines.

The goal of this issue was to create a reminder to discuss about it later.
It won't be hard to implement it.

**Comment by bourretp** [comment]
I remind using, with Felix, space-separated list of URLs to add some bundles to auto-start, it was something like that:
```
felix.auto.start.1=\
   http://repo1.maven.org/maven2/org/apache/felix/org.apache.felix.eventadmin/1.4.2/org.apache.felix.eventadmin-1.4.2.jar \
   http://repo1.maven.org/maven2/org/apache/felix/org.apache.felix.ipojo/1.12.1/org.apache.felix.ipojo-1.12.1.jar \
   http://repo1.maven.org/maven2/org/apache/felix/org.apache.felix.ipojo.handler.eventadmin/1.8.0/org.apache.felix.ipojo.handler.eventadmin-1.8.0.jar \
   …
```
Nothing really difficult there. Just a backslash at the end of each line...
This solution seems quite natural and URL-crap compatible (those with reserved-but-allowed characters like `,` `;`)

**Comment by vincent-zurczak** [comment]
You are right in fact, spaces are suitable.
I close this issue.
