### ISSUE TITLE
Rename the "openstack.nova-url" parameter

### ISSUE THREAD

**Issue by ykouki** [roboconf/roboconf-platform#414]
In the target.properties file for Openstack support, you need to replace the property "openstack.nova-url"  by "openstack.keystone-url". Indeed, to access Openstack services, you must specify the URL of keystone (Openstack's identity component) and not the URL of Nova (Openstack's compute component).

**Comment by vincent-zurczak** [comment]
Indeed, this parameter is not named correctly.
Apart renaming it, there is no other modification to apply.
