### ISSUE TITLE
Extend the DM API

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#419]
Currently, the DM is the only API class to interact with DM features.
Internally, it delegates most of the job to other classes. However, this makes the DM's code very messy.

What we should do is defining delegates API/interfaces.
Therefore, instead of writing... `manager.changeState( ... )`, we would rather invoke `manager.lifecycleDelegate().changeState( ... )`. Sure, it will make the code a little bit longer when we invoke such methods, but that would keep the Manager's code clean and easy to maintain.

Most of all, it would ease the definition of an API in the DM.
Currently, we update it on every release and indicating the changes each time is almost impossible.

Doing such a change right now is too dangerous.
However, new additions (such as target management) should set up this coding paradigm.

**Comment by vincent-zurczak** [comment]
I am wondering.
Maybe we should split the DM into several OSGi services. All of them would share a same configuration, but would remain independent.

**Comment by bourretp** [comment]
Dealing with #308 lead me to access the DM's `ApplicationTemplateMngrDelegate` object. I've added a getter `getTemplateManager()` method in the DM. See upcoming PR...

**Comment by vincent-zurczak** [comment]
:sob: 

We will see that. I am thinking to start working on this issue at the same time. Unit tests in the DM are not very nice to maintain...
