### ISSUE TITLE
Provide a way to define local configuration parameters

### ISSUE THREAD

**Issue by cdeneux** [roboconf/roboconf-platform#423]
In the Roboconf graph we can define configuration parameters as exported parameters that are used by other components of the Roboconf application. This is done using the keyword `exports`.

To define configuration parameters without exporting them, for example to configure thread pool sizes, queue sizes, ..., we must add these parameters directly into the instances definition, and we will get a warning at build time.
Moreover, this way does not permit to define default values. We must redefine such configuration parameters for each instance of a same component.

So, in my mind, a new keyword `locals` must be introduced in the Roboconf graph to manage such configuration parameters.

Example, in `graph.main`:

```
PetalsJBIComponent {
    installer: script;
    exports: componentId = my-component-id;
    locals: acceptorPoolSize = 4, processorPoolSize = 10, processorMaxPoolSize = 50;
    children: PetalsSU;
}

PetalsBC {
    extends: PetalsJBIComponent;
    installer: petals-bc-installer;
}

PetalsBCSoap {
    extends: PetalsBC;
    exports: httpPort = 8084;
    locals: httpServiceList = true, httpServiceContext = petals;
}
```

**Comment by cdeneux** [comment]
As proposed by #424, another new keyword ``local`` should be introduced to declare only one such parameter:

    PetalsJBIComponent {
        installer: script;
        export: componentId = my-component-id;
        local: acceptorPoolSize = 4;
        local: processorPoolSize = 10;
        local: processorMaxPoolSize = 50;
        children: PetalsSU;
    }

    PetalsBC {
        extends: PetalsJBIComponent;
        installer: petals-bc-installer;
    }

    PetalsBCSoap {
        extends: PetalsBC;
        export: httpPort = 8084;
        local: httpServiceList = true;
        local: httpServiceContext = petals;
    }

**Comment by vincent-zurczak** [comment]
You are not the first one to suggest the addition of such a parameter.
But IMO, it goes farther than just the DSL part. Given that one of the tasks performed by Roboconf consists in reconfiguration, there will probably be requirements about changing dynamically such parameters.

Anyway, if we had to accept this issue, we should restrain it to define new "local" parameters and inject them in recipes, scripts, etc...

@rpignolet I know you are very busy, but you might have an opinion about it.
I remember you once asked for it too.

PS: I am not sure **local** is a very good name.
On the same model than **exports** and **imports**, I would rather see something like **uses**.

**Comment by vincent-zurczak** [comment]
I have been thinking about it...
One of the reasons why I did not want such a keyword the first time I was asked about it, was that the graph defines relations between Software components. Local configuration parameters are related to recipes (e.g. scripts), not to relations. Changing your recipe should only require you to update the installer in the graph. I am not sure the graph is the right place for local parameters.

On the other hand, if we go forward a configuration and reconfiguration tool, then, it makes sense to put everything in the graph. So, this is more about the scope we want to give to Roboconf.

And if we add the notion of private variables (only visible in recipes), then I fear usual side effects. What would happen if someone suddently realized one of the local variables should be made public? Easy: he or she would have to update the graph and go through another release process. Or he, or she would ask for means to define dynamically the visibility of a variable. And that would be a useless complexity.

We could in fact keep all the variables as exported.
And they won't be used if no other component imports them. What was painful with exports was that they had to fit on a single line. But #424 provides a fix for that.

So, I really don't know if it is really useful.
If you want to define configurable (internal) parameters for your recipes, you can also provide a properties file (or any format you want) in your recipe and use it. This way, your recipe externalizes a part of its configuration, but it remains private and related to your recipe.

**Comment by vincent-zurczak** [comment]
Or we could also provide both ways (**exports** and **uses**) but define as a good practice to put everything in exports.
The interest of **uses** (or whatever is its name) is that Roboconf could propagate changes to an agent if an administrator wanted to update such values. But it means the recipe should also handle it in the **update** step. BTW, I think **update** is too vague. **reconfigure** would be a better name than **update**. **reconfigure** could imply a dependency has changed, but also that a configuration parameter was modified.

**Comment by vincent-zurczak** [comment]
I really wonder whether a new keyword is a good idea.
This can be achieved with exported variables. An internal variable is a variable that is exported but that no one imports. Potentially, any internal variable could be shared as soon as one imports it. What is missing is being able to change the value of an exported variable and trigger a **reconfigure** phase.
