### ISSUE TITLE
Allow to use keywords 'exports' and 'imports" several times

### ISSUE THREAD

**Issue by cdeneux** [roboconf/roboconf-platform#424]
The Roboconf graph supports keyword ``exports`` and ``imports`` to define configuration parameters used between linked applications.

These syntax is not really readable when we have a lot of parameters:

    PetalsRegistry {
        installer: script;
        exports: memberId = sample-member-0, ip, port = 7900, credentialsGroup = default-sample, credentialsPassword = s3cr3t, managementUrl = http://192.168.1.100:8080/mancenter;
    }

    PetalsRegistryMaster {
        extends: PetalsRegistry;
        imports: PetalsRegistry.memberId (optional), PetalsRegistry.ip (optional), PetalsRegistry.port (optional);
    }

It could be interesting to introduce two new keywords ``export`` and ``import`` accepting only one configuration parameter. These keywords could used several times.

    PetalsRegistry {
        installer: script;
        export: memberId = sample-member-0;
        export: ip;
        export: port = 7900;
        export: credentialsGroup = default-sample;
        export: credentialsPassword = s3cr3t;
        export: managementUrl = http://192.168.1.100:8080/mancenter;
    }

    PetalsRegistryMaster {
        extends: PetalsRegistry;
        import: PetalsRegistry.memberId (optional);
        import: PetalsRegistry.ip (optional);
        import: PetalsRegistry.port (optional);
    }

Of course, ``exports`` and ``export`` (and, ``imports`` and ``import``) can be mixed in the same definition. Both must declare different parameters.

**Comment by vincent-zurczak** [comment]
I don't like the idea of having 100 keywords in the DSL.
What could be done...

1. Allow to use break lines in exports and imports.
2. Allow to use exports and imports several times for a same component.

Which could give...

```
PetalsRegistry {
    installer: script;
    exports: memberId = \
        sample-member-0, \
        export: ip, \
        export: port = 7900, \
        export: credentialsGroup = default-sample, \
        export: credentialsPassword = s3cr3t, \
        export: managementUrl = http://192.168.1.100:8080/mancenter;
}
```

... or...

```
PetalsRegistry {
    installer: script;
    exports: memberId = sample-member-0;
    exports: ip;
    exports: port = 7900;
    exports: credentialsGroup = default-sample;
    exports: credentialsPassword = s3cr3t;
    exports: managementUrl = http://192.168.1.100:8080/mancenter;
}
```

IMO, the second option is indeed more readable.
Both **exports** and **imports** would keep the current list notation. We would thus just add a new one.

**Comment by cdeneux** [comment]
Caution, your first example is false. The right definition is something as:

    PetalsRegistry {
        installer: script;
        exports: \
            memberId = \
                sample-member-0, \
            ip, \
            port = 7900, \
            credentialsGroup = default-sample, \
            credentialsPassword = s3cr3t, \
            managementUrl = \
                http://192.168.1.100:8080/mancenter;
    }

IMO, for my need, the break line is sufficient and is more readable than your second proposal. To be able to use several times the keyword ``exports`` in the same component will be an extra feature.

**Comment by vincent-zurczak** [comment]
Indeed, my first example was incorrect.
I'm not fond of the line break with a back-slash... It's easy to forget one. Repeating the keyword is easier IMO.

**Comment by cdeneux** [comment]
Sure, but if a back-slash is missing, an error will occur at build time, and it is easy to fix it ;)

**Comment by vincent-zurczak** [comment]
Sure... But...

```
exports: \
        memberId = \
            sample-member-0, \
        ip, \
        port = 7900, \
        credentialsGroup = default-sample, \
        credentialsPassword = s3cr3t, \
        managementUrl = \
            http://192.168.1.100:8080/mancenter;
```

... is less readable than...

```
exports: memberId = sample-member-0;
exports: ip;
exports: port = 7900;
exports: credentialsGroup = default-sample;
exports: credentialsPassword = s3cr3t;
exports: managementUrl = http://192.168.1.100:8080/mancenter;
```

And reability was the initial requirement in this issue.
