### ISSUE TITLE
Inject the instance object in monitoring handlers

### ISSUE THREAD

**Issue by cdeneux** [roboconf/roboconf-platform#428]
The measure extension API provides the measured instance name as path but no way exists to retrieve the configuration parameters fro this instance path name.

The API ``MonitoringHandler.process()`` should change to ``MonitoringHandler.process(net.roboconf.model.beans.Instance instance)``. In this way, we can access configuration parameters of the current instance or its parents.

**Comment by vincent-zurczak** [comment]
The instance path only gives the identifiers of the agent.
You should not rely on them, nor modify them.

If you need instance information, we indeed need to pass the instance in the `process` method. This method is invoked for every instance associated with the measure handler. Remember, the measure handler is the same object for all the instances managed on this agent. Or, to be precise, the same object for all the instances that use the same handler.
