### ISSUE TITLE
Prevent the autonomic from executing a reaction twice

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#452]
@cdeneux has experienced the following problem.
He defined a reaction that replicates a VM. The agent polls every 10 seconds. So, when the probe is *stimulated*, the agent sends information to replicate a service. If the replication takes more than 10 seconds (the poll delay), then more than one VM will be created by the autonomic.

This is not very efficient.
We can implement a control on reactions.

If a reaction (identified by its ID) is already in progress for a given agent, then we should ignore others.
For the **replicate-service**, it means we cannot create a new service if the previously created on is not **DEPLOYED_AND_STARTED**. In the same way, we cannot delete a service with **delete-service** if the **previously deleted** instance still exists. Again, these verifications have to be made per agent (the one that requested the reaction).

This should prevent some dumb behaviors.

**Comment by vincent-zurczak** [comment]
In fact, it should not be blocking per reaction ID and per agent, but only per reaction.
Indeed, if two VM send the same request, only one should be undertaken. And the other one should be ignored, unless the first one completed.

We may also consider having a delay between the end of the first reaction end, and the beginning of a new one. I think 1 minute is good. Later, commands will be able to group reactions and therefore remove some limitations.

**Comment by cdeneux** [comment]
Why do you want to add a delay ?

**Comment by vincent-zurczak** [comment]
Let's consider the following scenario:

* T+0: the agent detects a threshold has been reached and sends a message.
* T+1: the DM receives the messages and reacts.
* T+10 (10 is the poll delay here): the agent detects a threshold has been reached and sends a message.
* T+11: the DM receives the messages and ignores it as the previous action is still on its way.
* ...
* T+29: the previous action completed (everything is deployed and started but there may be reconfiguration in progress).
* T+30: the agent detects a threshold has been reached and sends a message.
* T+31: the DM receives the messages and reacts.
* T+33: the reconfiguration completed and produces the expected results.

Having a short delay guarantees the agent's message (@ T+31) is relevant and that the reconfiguration completed.

**Comment by vincent-zurczak** [comment]
The delay thing will be done in another issue.
