### ISSUE TITLE
[Autonomic] We should be able to change instance name with reaction 'Replicate Instance'

### ISSUE THREAD

**Issue by cdeneux** [roboconf/roboconf-platform#494]
I'm using the reaction 'Replicate Instance' to create a new instance of a full VM, with its all children. One of these children must have an unique name over all VM, so please provide a mechanism to re-write instance names, for example using a placeholder as "${random}",

    [reaction check-requests-nb-on-bc-soap-upper-5 Replicate-Instance]
    container-vm-1 where container-vm-1/container-node --> container-vm-${random}/container-node-${random}

**Comment by vincent-zurczak** [comment]
For version 0.5, we will provide a simple solution for the **replicate-instance** reaction.
But this will be entirely updated when we rework the autonomic with the commands framework.

**Comment by vincent-zurczak** [comment]
Non-official documentation of this feature...

```
[reaction replicated Replicate-Instance]
container-vm-1 WHERE %2 with CPT
```

The name of the first children of **container-vm-1** will be appended with "_" and an integer.

* %1 => root instance
* %2 => children instances
* %3 => grand-children instances
* Etc.
