### ISSUE TITLE
[ Agent ] Stop and undeploy should invoke all the scripts

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#495]
Currently, there is one hypothesis done on the agent side about stop and undeploy.
When we stop and/or undeploy something, we assume it will indirectly do the same for children. Said differently, if B is a child instance of A, and that we stop A, we do not stop B, since we thing stopping A will also stop B.

This assumption is right most of the time.
However, it might not always be true. In such cases, the impact is unpredictable. We should invoke all the scripts correctly. The behavior will then be more logical for those that implement recipes.

**Comment by rpignolet** [comment]
Oh, in the case of stop, you must call stop on children before the parent one. I thought that was the actual case.
If a component C import a variable of B, the C component will be notified about the stop of B ?

**Comment by vincent-zurczak** [comment]
The exports and so on are applied on all the children instances.
So, yes, component C will be notified.

But not all the scripts are invoked. Not yet.

**Comment by vincent-zurczak** [comment]
This is not that hard to implement, but this may have a major impact on the way we use Roboconf. We really need to think about this.

**Comment by vincent-zurczak** [comment]
After thinking about it, this is a design issue with respect to what recipes should do.
Roboconf sends the right notifications when elements are stopped. Actions should be undertaken upon notifications. So, we need to explain it on the web site.

**Comment by vincent-zurczak** [comment]
Done. See http://roboconf.net/en/user-guide-snapshot/good-practices-for-recipes.html
