### ISSUE TITLE
Force a Maven update when installing a bundle with a Maven URL

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#499]
Whe installing a bundle with a Maven URL, Karaf first looks in the local repository.
However, if there is a more recent version of the bundle on a remote repository, Karaf will use the local one while the remote one should be picked up.

This is in particular true for snapshot versions.
We should see if there is a way to enable such a resolution mechanism in Karaf.

**Comment by vincent-zurczak** [comment]
According to [KARAF-2183](https://issues.apache.org/jira/browse/KARAF-2183) it is already possible to force such an update. By reading [PAX URL's documentation](https://ops4j1.jira.com/wiki/display/paxurl/Mvn+Protocol), it seems we can add the `org.ops4j.pax.url.mvn.globalUpdatePolicy` property in Karaf's **etc/org.ops4j.pax.url.mvn.cfg**.

To test...
If working, this should be added on the web site in the advanced section tips.

**Comment by vincent-zurczak** [comment]
Here is a testing protocol:

**Preparation**

* Test with the DM (Roboconf 0.6-SNAPSHOT).
* Modify a target (e.g. in-memory). Add a `System.out.println` statement somewhere.
* Compile it. Your local version will be different than the remote one.
* Force a build refresh on Travis. The remote version will be more recent.

**Verification**

* Install the **in-memory** target in the DM. Verify the logs. Your printing should appear.
* Uninstall it.
* Update the PAX configuration.
* Install the **in-memory** target in the DM. Verify the logs. Your printing should NOT appear.

The installed version will have been taken on the remote repository since it is more recent than the build snaphot).

> Verify the time zone is the same on Travis and your system!

**Comment by cdeneux** [comment]
Yes, it is interesting to be able to get always the last snapshot

**Comment by vincent-zurczak** [comment]
Verified and working as expected.
Documented [here](http://roboconf.net/en/user-guide-snapshot/configuring-the-deployment-manager.html) and in the last released user guide.
