### ISSUE TITLE
Maximum number of instances created by the autonomic has been reached

### ISSUE THREAD

**Issue by cdeneux** [roboconf/roboconf-platform#500]
It seems that the instance number created by autonomic is not decrease when removing an instance created by autonomic, from Roboconf web-console.
That's why I get the log trace ``maximum number of instances created by the autonomic has been reached`` on new creation try after to have remove all instances created by autonomic

**Comment by vincent-zurczak** [comment]
Indeed, when an autonomic instance is deleted by hand, we should decrease the counter of the VM created by the autonomic.

**Comment by vincent-zurczak** [comment]
BTW, this is our 500<sup>th</sup> issue! :birthday:
