### ISSUE TITLE
Improve integration of Maven and application descriptor

### ISSUE THREAD

**Issue by cdeneux** [roboconf/roboconf-platform#507]
In the application descriptor of a Roboconf application we can set value as version:

    application-name = Tomcat 8 cluster
    application-qualifier = tomcat8-cluster-1.0.0-SNAPSHOT

To avoid to change the value of ``application-qualifier`` before to release our Roboconf application, we should be able to use a definition as:

    application-name = Tomcat 8 cluster
    application-qualifier = ${project.artifactId}-${project.version}

More generally, all Maven properties should be usable into the application descriptor.

**Comment by vincent-zurczak** [comment]
It already works.

**Comment by cdeneux** [comment]
Super, but it is not documented on page http://roboconf.net/en/user-guide/application-descriptor.html ;)

**Comment by vincent-zurczak** [comment]
No, it's not.
I have other updates in progress, it will be part of it.

**Comment by vincent-zurczak** [comment]
Documentation was updated.
