### ISSUE TITLE
maven plugin: support dependencies in reactor build

### ISSUE THREAD

**Issue by victornoel** [roboconf/roboconf-platform#508]
Considering the following situation: building a multi-module project with two different modules (A and B) using roboconf-maven-plugin and the project A depends on the project B (see https://github.com/petalslink/petals-virtual-container/ for an example, pvc-soa-app-sample as A which depends on petals-pvc as B).

Then, currently, when roboconf-maven-plugin tries to access the dependency B when building A, it does not access to the files in the reactor build (i.e., directly in the target directory of B) but instead access to the installed artefact in the local repository.
This can be problematic if the multi-module build is done with "mvn package" and the artefact has never been installed before. More severe, this can cause inconsistencies if an old version of B is installed and the multi-module build is done with "mvn install"…
Finally, this also shows an inconsistency between the point of view of maven and dependency management (maven considers the dependency to be resolved from the reactor build) and the point of view of roboconf-maven-plugin (it directly look into the local repository without relying on maven for accessing its dependencies).

roboconf-maven-plugin should be able, in case of multi-module build, to directly use the artefact as if it is resolved in the reactor and not from the local repository. Of course, if it is not currently resolved as part of the reactor, this makes no sense and the artefact should be fetched like any maven dependency.

Note that it is how many maven plugin works (think for example about maven-compiler-plugin that look for dependencies' classes either in the multi-module build or in the local repository, after downloading them as part as the normal dependency resolution).

**Comment by vincent-zurczak** [comment]
Hint for later: update the **resolve** mojo.

**Comment by vincent-zurczak** [comment]
OK...

```
Finally, this also shows an inconsistency between the point of view of maven and dependency
management (maven considers the dependency to be resolved from the reactor build) and the point
of view of roboconf-maven-plugin (it directly look into the local repository without relying on maven
for accessing its dependencies).

roboconf-maven-plugin should be able, in case of multi-module build, to directly use the artefact as if
it is resolved in the reactor and not from the local repository. Of course, if it is not currently resolved 
as part of the reactor, this makes no sense and the artefact should be fetched like any maven 
dependency.

Note that it is how many maven plugin works (think for example about maven-compiler-plugin that look for dependencies' classes either in the multi-module build or in the local repository, after downloading them as part as the normal dependency resolution).
```

Here is what I did. I verified your assertions.

I created a multi-module project with two Java modules, A and B. B depends on A. I then run `mvn clean package` and... I got a build failure on B because A was not on Central and in the local repositories. And A had been compiled and packaged in the same reactor. I looked at the options of the Maven compiler plugin and I did not see anything that would allow to resolve dependencies location directly in the reactor. I also looked in the code of the Maven compiler plugin and I did not see any introspection of the dependencies.

So, be it a Java or a Roboconf project, when dealing with multi-module projects, you always have to use `mvn install` before working on a specific module. You can also do the test with Petals ESB. Clear a part of your local repository and try to package a part fo the project. You will experience the same error.

I will thus mark this bug as invalid.
If you find a counterexample, feel free to reopen it.

**Comment by victornoel** [comment]
Hi, are you sure you actually made a reactor build with a pom.xml in the directory containing the two other projects that declares the two modules?

And that you called mvn clean package from the directory containing this pom.xml?

I just did a test and it works, that's the whole point of having multi-module projects in maven…
See: https://gist.github.com/victornoel/344106b2983586fd596d (each of the testX-pom.xml must be renamed to file in subdirectories testX/pom.xml of course).

You can add java file that references each other to be more "realistic".

Here are the result of running mvn clean package:
```
➜  test  mvn clean package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] test2
[INFO] test1
[INFO] reactor
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building test2 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ test2 ---
[INFO] Deleting /home/vnoel/Linagora/Petals/dev/test/test2/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ test2 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/vnoel/Linagora/Petals/dev/test/test2/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ test2 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/vnoel/Linagora/Petals/dev/test/test2/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ test2 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/vnoel/Linagora/Petals/dev/test/test2/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ test2 ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ test2 ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ test2 ---
[INFO] Building jar: /home/vnoel/Linagora/Petals/dev/test/test2/target/test2-1.0.jar
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building test1 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ test1 ---
[INFO] Deleting /home/vnoel/Linagora/Petals/dev/test/test1/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ test1 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/vnoel/Linagora/Petals/dev/test/test1/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ test1 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/vnoel/Linagora/Petals/dev/test/test1/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ test1 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/vnoel/Linagora/Petals/dev/test/test1/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ test1 ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ test1 ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ test1 ---
[INFO] Building jar: /home/vnoel/Linagora/Petals/dev/test/test1/target/test1-1.0.jar
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building reactor 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ reactor ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] test2 .............................................. SUCCESS [  1.777 s]
[INFO] test1 .............................................. SUCCESS [  0.074 s]
[INFO] reactor ............................................ SUCCESS [  0.003 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.962 s
[INFO] Finished at: 2016-01-06T10:48:00+01:00
[INFO] Final Memory: 15M/211M
[INFO] ------------------------------------------------------------------------
```

**Comment by vincent-zurczak** [comment]
That's weird. I made the exact same test (with a Java class in both projects) and it failed. I will investigate it a little more.

**Comment by vincent-zurczak** [comment]
Indeed, it works.
I had made a typo in my sample. So, we need to update the way we resolve artifacts locations.

**Comment by vincent-zurczak** [comment]
OK. I finally fixed it. This will be part of our next release.
BTW, I tested it on the Petals PVC and the POM files are not all up to date. Some children modules reference the released parent while the parent is now in snpashot version. That would be fine with a SVN. But with Git, releasing one module will tag the entire repository.

**Comment by victornoel** [comment]
Great, nice work! Thanks for the tips for the PVC, I will check that :)
