### ISSUE TITLE
Support Block Storage on AWS

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#513]
Add the following options in the AWS target handler.

* **ebs-size**: the size (in GB) of the block.
* **ebs-mount-point**: the mount point (e.g. */mnt/deva*).
* **ebs-type** the type of storage (see [EBS volumes](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumes.html)).
* **ebs-delete-on-termination**: true to delete the storage when the VM is terminated, false otherwise (true by default).

Plus, maybe, other options that might be significative to users.

**Comment by vincent-zurczak** [comment]
Please, add an option **use-block-storage**.
When set, it means we want to use block storage. And use fault values for others storage options (e.g. 5 GB for the size and */dev/sda* for the mount point).

**Comment by vincent-zurczak** [comment]
Please, think about updating the documentation on the web site about this new feature.

**Comment by gibello** [comment]
Done.

Season greetings,
  Pierre-Yves G.
