### ISSUE TITLE
Add an "ip" parameter in the in-memory handler

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#517]
When the **in-memory** handler is used to simulate plug-ins, there is no problem in using *localhost* as the IP address of the agents. However, when running real recipes, as specified in #516, we should be able to specify a different one (or even let the agent guess it).

This behavior is really useful when deploying local Docker containers through scripts.

**Comment by gibello** [comment]
Le 05/11/2015 14:23, Vincent Zurczak a écrit :
>
> When the *in-memory* handler is used to simulate plug-ins, there is no 
> problem in using /localhost/ as the IP address of the agents. However, 
> when running real recipes, as specified in #516 
> <https://github.com/roboconf/roboconf-platform/pull/516>, we should be 
> able to specify a different one (or even let the agent guess it).
>
> This behavior is really useful when deploying local Docker containers 
> through scripts.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/roboconf/roboconf-platform/issues/517>.
>
Generally Docker sets up a local network interface which is a kind of 
localhost "alias", but is on the same subnet as docker containers.

Example from my local host (ifconfig -a):
docker0   Link encap:Ethernet  HWaddr 56:84:7a:fe:97:99
           inet adr:172.17.42.1  Bcast:0.0.0.0  Masque:255.255.0.0

For most docker use-cases, it is better here to use 172.17.42.1 as 
localhost IP address.

Not sure this address is always the same, or if we need some way to 
retrieve its value ?

**Comment by vincent-zurczak** [comment]
What IP address to use does not matter.
What matters is that we can set one through the in-memory configuration. :wink: 
Anyway, we can add this information on the web site.

**Comment by vincent-zurczak** [comment]
OK, I added this information on the web site (commit to come before noon).
