### ISSUE TITLE
Unable to join the HTTP docker API on Ubuntu 15.10

### ISSUE THREAD

**Issue by cdeneux** [roboconf/roboconf-platform#564]
When installing Roboconf on Ubuntu 15.10 to deploy Docker container, we can get errors because Roboconf DM is unable to join the HTTP docker API even if you have correctly set the file `/etc/default/docker` with the content of `DOCKER_OPTS` defined here: http://roboconf.net/en/user-guide/docker-tips.html.

This is problem is due to a bug in the Docker package for Ubuntu 15.10. Just apply the patch https://github.com/mattelacchiato/docker/commit/41d6594e832c225525ceb9e82a63e1b5522f6498 to retrieve the HTTP Docker API enable.

**Comment by vincent-zurczak** [comment]
Thanks for the tip. :+1: 
It will let a trace for others.
