### ISSUE TITLE
[ iaas-openstack ] Allow explicit declaration of a region

### ISSUE THREAD

**Issue by BastienM** [roboconf/roboconf-platform#569]
It would be nice for the region to have its own option (eg. ```openstack.region-name``` or ```openstack.region-id```).

The way a region is currently handled is a but confusing as its name isn't straightforward and asks for the flavor's ID (which isn't always easily available to the user).
```
openstack.image-id = RegionOne/abcdef
openstack.hardware-id = RegionOne/2
```

**Comment by vincent-zurczak** [comment]
When not specified, the first found zone will be taken.
Otherwise, we will use the given one.

Or should we make this parameter mandatory?

**Comment by BastienM** [comment]
The if-else behavior should do the trick.
The autoselection is indeed nice when rolling a single zone Openstack. And being able to specify a zone when needed will put too much rework of the current system.
