### ISSUE TITLE
"Deploy this instance" button not working

### ISSUE THREAD

**Issue by BastienM** [roboconf/roboconf-platform#597]
Since release 0.6, clicking on the button **Deploy this instance** doesn't trigger anything (on the webui or in the logs).

We must use the **Deploy and Start everything** button to activate the action.
Same thing goes for undeploying.

**Comment by vincent-zurczak** [comment]
OK. I confirm this is a bug with the web console.  :fearful: 
I don't know how we missed it. :scream: 

Fixing it can be done very quickly.
But the question of a maintenance release is now on the table.

I suggest we investigate your other issues first.
Then, we will release a maintenance version (0.6.1).
