### ISSUE TITLE
Create a deployment target for OCCI-Infrastructure

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#599]
1. Identify the target properties.
2. Create a bundle for such targets.

Here are some resources that may help:
- http://occi-wg.org/about/specification/
- https://github.com/jeanparpaillon/occi-schemas/blob/master/xml/occi-infrastructure.xml

There may be some Java clients here and there.
Here is [one licensed under the LGPL v3](https://github.com/occi4java/occi4java). See also http://occi-wg.org/tag/java/

However, it may not be that hard to create one with Jersey.
Licence and dependencies need to be verified.

**Comment by vincent-zurczak** [comment]
Hi @gibello. Could you elaborate a little roadmap for the OCCI infrastructure target?
Should we close this issue and consider the basis exists? Or should we wait for new improvements (e.g. user data) before closing it?

Basically, if there are new items to come, it might be better to dedicate them new issues. WDYT about it? :smiling_imp:

**Comment by gibello** [comment]
Yes, the basics work (creating VMs). But the missing part is user data 
(roboconf can just create VMs but they never obtain the deployed/started 
state).

Can be a later issue, indeed. It should be implemented soon, and is part 
of OCCI infra 1.2.

**Comment by vincent-zurczak** [comment]
OK. I let you create a dedicated issue for user data.
And let's close this one.
