### ISSUE TITLE
Components and facets with space in their name

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#626]
1. Create a component whose name contains a space.
2. Try to import some of its variables in another component.
3. Validate the graph.

There is an inconsistency.
Variable names cannot contain spaces!

**Comment by vincent-zurczak** [comment]
We have unit tests that verify we can define components and facets with spaces in their names.
But we have nothing to verify variables, whose names include the type's one.

So, we made inconsistent choices.
Either we allow spaces in variable names, or we forbid them in type names. Given that variables are used in plug-ins (e.g. scripts), it is better to forbid spaces in type names. Basically, we revert a change we made quite a long time ago.

**Comment by gibello** [comment]
I think forbidding spaces is the right way to go. The more we forbid 
spaces in names, the less we have problems !

**Comment by vincent-zurczak** [comment]
Yes, spaces will not be allowed anymore in component and facet names.
