### ISSUE TITLE
Test the DM with clustered RabbitMQ servers

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#665]
To verify for fail-over scenarios.
Add documentation on the web site. And maybe upgrade the DM and agent parameters (e.g. use a list of RMQ IPs).

**Comment by gibello** [comment]
Just done the following test on Docker, works: so it seems OK with a 
2-node cluster, keeps working if we stop/start one of the nodes.
Will publish documentation soon...

On node rabbit1 :
=================
rabbit1$ rabbitmq-server -detached

rabbit1$ rabbitmqctl cluster_status
Cluster status of node rabbit@rabbit1 ...
[{nodes,[{disc,[rabbit@rabbit1]}]},{running_nodes,[rabbit@rabbit1]}]
...done.

Create roboconf user (on one node):
rabbitmqctl add_user roboconf roboconf
rabbitmqctl set_permissions roboconf ".*" ".*" ".*"


On node rabbit2 :
=================
- Declare node rabbit1 in /etc/hosts
- Edit /var/lib/rabbitmq/.erlang.cookie, and insert the same content as 
on node rabbit1.

rabbit2$ rabbitmq-server -detached
rabbit2$ rabbitmqctl stop_app
Stopping node rabbit@rabbit2 ...done.
rabbit2$ rabbitmqctl join_cluster rabbit@rabbit1
Clustering node rabbit@rabbit2 with [rabbit@rabbit1] ...done.
rabbit2$ rabbitmqctl start_app
Starting node rabbit@rabbit2 ...done.

Testing
=======

Start roboconf DM with node rabbit1 as messaging server.
Upload an application with dependencies (eg. apache/tomcat).
Test messaging with apache started, then alternately start/stom tomcat 
and check apache status change.

Then:
- Stop node rabbit2:
rabbitmqctl stop
(check status on rabbit1 :
rabbit1$ rabbitmqctl cluster_status)

- Test again : alternately start/stom tomcat and check apache status change.

- Restart node rabbit2
rabbitmq-server -detached
(check status on rabbit1 :
rabbit1$ rabbitmqctl cluster_status)

- Test again : alternately start/stom tomcat and check apache status change.

**Comment by vincent-zurczak** [comment]
It looks great. :+1: 
But I may have misunderstood something.

```
Start roboconf DM with node rabbit1 as messaging server. 
Upload an application with dependencies (eg. apache/tomcat). 
Test messaging with apache started, then alternately start/stom tomcat and check apache status change. 

Then: - Stop node rabbit2: rabbitmqctl stop (check status on rabbit1 : rabbit1$ rabbitmqctl cluster_status)
```

So, you start the DM using RabbitMQ 1.
And then you stop RabbitMQ 2 ?  :alien:

What would be interested would be to stop RabbitMQ 1 and see whether the DM and agents automatically switch to RabbitMQ 2.

**Comment by gibello** [comment]
Le 22/07/2016 à 12:04, Vincent Zurczak a écrit :
>
> It looks great. 👍
> But I may have misunderstood something.
>
> |Start roboconf DM with node rabbit1 as messaging server. Upload an 
> application with dependencies (eg. apache/tomcat). Test messaging with 
> apache started, then alternately start/stom tomcat and check apache 
> status change. Then: - Stop node rabbit2: rabbitmqctl stop (check 
> status on rabbit1 : rabbit1$ rabbitmqctl cluster_status) |
>
> So, you start the DM using RabbitMQ 1.
> And then you stop RabbitMQ 2 ? 👽
>
> What would be interested would be to stop RabbitMQ 1 and see whether 
> the DM and agents automatically switch to RabbitMQ 2.
>
No, it does not work.

The system works again when I restart node 1, but not while node1 is 
stopped.
So the client probably does not handle automatically the switch (don't 
know if it is possible, but currently it is not the case).

**Comment by vincent-zurczak** [comment]
OK. Indeed, documentation about it will be appreciated.
You can also add...

```
Connecting to Clusters from Clients

A client can connect as normal to any node within a cluster. If that node should fail, and the rest of the cluster survives, then the client should notice the closed connection, and should be able to reconnect to some surviving member of the cluster. Generally, it's not advisable to bake in node hostnames or IP addresses into client applications: this introduces inflexibility and will require client applications to be edited, recompiled and redeployed should the configuration of the cluster change or the number of nodes in the cluster change. Instead, we recommend a more abstracted approach: this could be a dynamic DNS service which has a very short TTL configuration, or a plain TCP load balancer, or some sort of mobile IP achieved with pacemaker or similar technologies. In general, this aspect of managing the connection to nodes within a cluster is beyond the scope of RabbitMQ itself, and we recommend the use of other technologies designed specifically to solve these problems. 
```

From https://www.rabbitmq.com/clustering.html#clients
And...

```
Clustering

Clustering connects multiple machines together to form a single logical broker. Communication is via Erlang message-passing, so all nodes in the cluster must have the same Erlang cookie. The network links between machines in a cluster must be reliable, and all machines in the cluster must run the same versions of RabbitMQ and Erlang.

Virtual hosts, exchanges, users, and permissions are automatically mirrored across all nodes in a cluster. Queues may be located on a single node, or mirrored across multiple nodes. A client connecting to any node in a cluster can see all queues in the cluster, even if they are not located on that node.

Typically you would use clustering for high availability and increased throughput, with machines in a single location. 
```

From https://www.rabbitmq.com/distributed.html
Basically, what it means is that clusters only allow to distribute the charge but do not cover fail-over cases. For such situations, it seems we need to setup a load balancer and reference it in our messaging configuration.

Would it be possible to test (later) what kind of load balancer we can use for such a scenario?

**Comment by gibello** [comment]
Load-balancing for failover can be done using haproxy (doc follows, to 
be published).
Any LB should be usable, including the one provided on AWS for cloud 
deployment on EC2.

Haproxy doc update (tested using 3 docker containers, 2 for rabbit nodes 
and 1 for haproxy):

On node rabbit1:
================
rabbit1$ rabbitmq-server -detached

rabbit1$ rabbitmqctl cluster_status
Cluster status of node rabbit@rabbit1 ...
[{nodes,[{disc,[rabbit@rabbit1]}]},{running_nodes,[rabbit@rabbit1]}]
...done.

Create roboconf user (on one node):
rabbitmqctl add_user roboconf roboconf
rabbitmqctl set_permissions roboconf ".*" ".*" ".*"


On node rabbit2:
================
- Declare node rabbit1 in /etc/hosts
- Edit /var/lib/rabbitmq/.erlang.cookie, and insert the same content as 
on node rabbit1. (note: if creating the file, make sure it belongs to 
rabbitmq:rabbitmq with access rights restricted to 400).

rabbit2$ rabbitmq-server -detached
rabbit2$ rabbitmqctl stop_app
Stopping node rabbit@rabbit2 ...done.
rabbit2$ rabbitmqctl join_cluster rabbit@rabbit1
Clustering node rabbit@rabbit2 with [rabbit@rabbit1] ...done.
rabbit2$ rabbitmqctl start_app
Starting node rabbit@rabbit2 ...done.

On node haproxy:
================
apt-get install haproxy

Edit /etc/haproxy/haproxy.cfg, then add the following:
listen rabbitcluster 0.0.0.0:5672
          mode tcp
          option tcplog
          server rabbit-01 <IP-of-node-rabbit1>:5672 check fall 3 rise 2
          server rabbit-02 <IP-of-node-rabbit2>:5672 check fall 3 rise 2

Start haproxy:
sudo /usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg -D -p 
/var/run/haproxy.pid

Testing
=======

Start roboconf DM with node haproxy as messaging server.

Upload an application with dependencies (eg. apache/tomcat).
Test messaging with apache started, then alternately start/stom tomcat 
and check apache status change.

Then:
- Stop either node rabbit1 or rabbit2:
rabbitmqctl stop
(check status on node:
rabbitmqctl cluster_status)

- Test again : alternately start/stom tomcat and check apache status change.

- Restart node proviously stopped
rabbitmq-server -detached
(check status on node:
rabbitmqctl cluster_status)

- Test again : alternately start/stop tomcat and check apache status change.

**Comment by gibello** [comment]
For HAProxy load-balancing in clustering mode, client and server 
timeouts must be set to a long period, otherwise idle connections may 
get closed by HAProxy, causing errors.

Sample config (/etc/haproxy/haproxy.cfg):

listen rabbitcluster 0.0.0.0:5672
          mode tcp
          option tcplog
          timeout client  3h
          timeout server  3h
          server rabbit-01 <IP-of-node-rabbit1>:5672 check fall 3 rise 2
          server rabbit-02 <IP-of-node-rabbit2>:5672 check fall 3 rise 2

**Comment by vincent-zurczak** [comment]
A timeout of 3 hours? Seriously?

**Comment by gibello** [comment]
Don't know if I can make it infinite. The timeout just says that if no 
message is sent, the connection is supposed dead (then closed by haproxy).

For the user, 3 hours means exactly the same thing than stopping 
rabbitmq after 3 hours if no message is sent. By default it was 50 
seconds (which caused the bug we noticed).

**Comment by vincent-zurczak** [comment]
It may due to RMQ having micro-connections to the clients to maintain the connections alive. In this case, we would also have to configure the load balancer as a reverse proxy. Or we may also not recommend clustering with RabbitMQ, as it seems quite limited.

You should write a page about it on the web site, to be referenced in the **all-advanced-topics** page.
Please, mention the following links too:

* https://www.rabbitmq.com/distributed.html
* https://www.rabbitmq.com/clustering.html

**Comment by vincent-zurczak** [comment]
We should also write something about https://www.rabbitmq.com/ha.html and how it compares with what we described about clustering. :wink:

**Comment by vincent-zurczak** [comment]
This article is also a good link: https://insidethecpu.com/2014/11/17/load-balancing-a-rabbitmq-cluster/

**Comment by vincent-zurczak** [comment]
Documented [here](http://roboconf.net/en/user-guide-snapshot/clustered-rabbitmq.html).
