### ISSUE TITLE
Warn users when they import recipes or apps with target properties

### ISSUE THREAD

**Issue by cdeneux** [roboconf/roboconf-platform#689]
Now, the target id is unique through all targets of all applications deployed.

If you have 2 applications based on a same import containing a target definition, the id of this target will not be unique if both applications are deployed on the same Roboconf instance.

A solution must be found to prevent this use-case, for example avoiding definition of target in an import.

**Comment by vincent-zurczak** [comment]
Graph import relies on the Maven plug-in.
So, the Maven plug-in should introspect imported projects and verify they do not container target properties. A warning should be addressed in such cases.

**Comment by cdeneux** [comment]
IMO, a warning is not sufficient because it will be invisible in all traces generated by Maven.

Perhaps the solution could take place at the moment deploying the Roboconf application:
  - when deploying an application, if a target is embedded and already exists (deployed by another application, or by a target deployment), the deployment fails with message explaining that the current application must be reviewed to use Roboconf best-practices (ie, the target definition should be externalized),
  - so, if both applications are based on a same import, the import can be change to externalize the target and all will works fine.

**Comment by vincent-zurczak** [comment]
Once zipped, it is not possible to determine whether an application was built using imports or not. Reusable recipes are a build thing.

**Comment by cdeneux** [comment]
I think that you didn't understand what I mean.

When deploying an application, if it contains a target, the target will be deployed. If the target was previously deployed (by another application or by a target archive), an error occurs. So, the application deployment fails. In the error message, just explain to use Roboconf best-practices.

I'm no more sure that we should prevent this use case at build time.

**Comment by vincent-zurczak** [comment]
Since #690, the ZIP deployment already fails if it contains a target that was already deployed.
Anyway, we should keep this issue to add a warning in the Maven plug-in, when we import another project.
