### ISSUE TITLE
Unable to redeploy an application template (target id already exists)

### ISSUE THREAD

**Issue by cdeneux** [roboconf/roboconf-platform#692]
With the Roboconf Admin Console:
1. Create and Upload an application template containing the target definition. The application template is correctly created
2. Delete the application template previouly uploaded,
3. Re-create and re-upload the application template. An error occurs because of unicity of the target id. When removing the application template, the target definition was not removed and so the second deployment failed because the target definition already exists.

IMO, if deployed _with_ an application template, a target definition _must_ be linked to this application template to be automatically deleted when deleting the application template. It has no sens to keep this target definition registered because no other application will use it.

**Comment by vincent-zurczak** [comment]
Well...

> No other application will use it.

This is not always true.
We need to investigate this situation a little bit more.

**Comment by vincent-zurczak** [comment]
OK. We have the concept of « hint » for deployment targets.
So, when we undeploy an application template, all the targets that have a hint for this template, should be deleted as well.

**Comment by vincent-zurczak** [comment]
Well, using hints works... but may lead to unexpected situations.
We need a way to redefine target properties in some cases.
