### ISSUE TITLE
'docker.additional.deploy' should support Maven URL

### ISSUE THREAD

**Issue by cdeneux** [roboconf/roboconf-platform#694]
In the context of target Docker, `docker.additional.deploy` is used to add extensions to the Roboconf agent. When developing such extension with maven, it is not really simple to use a standard URL (`http` or `file`) because it must be completely changed when the extension is released.

It will be easier to use a Maven URL (`mvn:org.ow2.petals/petals-roboconf-plugin/1.0.1-SNAPSHOT`), for which only the version part is to be changed.

**Comment by vincent-zurczak** [comment]
We should inject Karaf's MavenResolver service.
In fact, this service seems to be inected by PAX-URL, but configured by Karaf (to be verified).

We should then be able to retrieve Maven artifacts.
