### ISSUE TITLE
Problem with rabbitmq when the DM is restarted.

### ISSUE THREAD

**Issue by diarraa** [roboconf/roboconf-platform#706]
Indeed, a rabbitmq client is not created when the DM is restarted. So it's not possible for the DM to communicate with an agent. The test scenario was done with the attached LAMP application. 
[lamp-webapp-bash-0.3.0-1.0.zip](https://github.com/roboconf/roboconf-platform/files/548453/lamp-webapp-bash-0.3.0-1.0.zip)

**Comment by vincent-zurczak** [comment]
Is this still a bug or was it due to your modifications?

**Comment by vincent-zurczak** [comment]
I guess it was a temporary bug due to your developments. :smiling_imp:

**Comment by diarraa** [comment]
It was a temporary bug. Now It's ok.
