### ISSUE TITLE
Add WAMP as messaging protocol and service

### ISSUE THREAD

**Issue by donsez** [roboconf/roboconf-platform#73]
Add WAMP as messaging protocol and service

WAMP (Web Application Messaging Protocol) is an open WebSocket subprotocol that provides two application messaging patterns in one unified protocol: Remote Procedure Calls + Publish-Subscribe

    http://wamp.ws/spec/
    https://github.com/tavendo/WAMP/blob/master/spec/basic.md
    https://github.com/tavendo/WAMP/blob/master/spec/advanced.md

**Comment by vincent-zurczak** [comment]
Somehow a duplicate of #459.
