### ISSUE TITLE
Make command files error handling more user-friendly

### ISSUE THREAD

**Issue by gibello** [roboconf/roboconf-platform#802]
At least 2 issues concerning error handling for command files, to make their usage more friendly:
- Error messages should contain the file name (messages like "No valid instruction was found in the file." or "A variable is used in a command but it could not be resolved." do not give any clue about which file is concerned).
- Empty command files should be allowed (or maybe files with only comments ?). Would be useful at development phase (at least a WARNING could be raised, instead of a SEVERE error...)

**Comment by vincent-zurczak** [comment]
Point 1 can be addressed by sending the error details in the web console.
Point 2 can be fixed by changing the error level in the core.

**Comment by vincent-zurczak** [comment]
Where did you get the problem?
The Maven plug-in shows every information you need. Was it in the web administration?
